export const XRICK_CONTROL = Object.freeze({
  RIGHT: 0x01,
  LEFT: 0x02,
  DOWN: 0x04,
  UP: 0x08,
  FIRE: 0x10,
  EXIT: 0x20,
  END: 0x40,
  PAUSE: 0x80
});

export const XRICK_GAMEPLAY_CONTROL_BY_NAME = Object.freeze({
  right: XRICK_CONTROL.RIGHT,
  left: XRICK_CONTROL.LEFT,
  down: XRICK_CONTROL.DOWN,
  up: XRICK_CONTROL.UP,
  fire: XRICK_CONTROL.FIRE
});

export const XRICK_MAP_EDITOR_CONTROL_BY_CODE = Object.freeze({
  ArrowUp:XRICK_CONTROL.UP, KeyO:XRICK_CONTROL.UP,
  ArrowDown:XRICK_CONTROL.DOWN, KeyK:XRICK_CONTROL.DOWN,
  ArrowLeft:XRICK_CONTROL.LEFT, KeyZ:XRICK_CONTROL.LEFT,
  ArrowRight:XRICK_CONTROL.RIGHT, KeyX:XRICK_CONTROL.RIGHT,
  Space:XRICK_CONTROL.FIRE
});
