import { PERCEPTUAL_FINGERPRINT_AXES, assertSoundLabManifest, bindingFor, energyForStrength, fingerprintDistance, interpretSoundDescription, materialOptions, outputsFor, perceptualFingerprint, perceptualSoundDescription, referenceLibrary, resourceOptions, resolvePreviewResources, sceneMotionSamples, sceneSoundIntent, sourceOptions, strengthForEnergy, telemetryTrace } from './rdx/src/soundlab/model.js';
import { renderSoundPreview, audioBufferFrom } from './rdx/src/soundlab/preview-renderer.js';
import { SoundLabAuthoringClient } from './rdx/src/soundlab/authoring-client.js';

const $=id=>document.getElementById(id);
const numeric=id=>Number($(id).value);
const state={manifest:null,manifestUrl:null,binding:null,preview:null,audio:null,decoded:new Map(),displayProfile:'preview',events:[],selectedEvent:-1,scene:null,sceneWindow:null,runtime:null,sceneReplayMode:'native',sceneDraftSource:null,auditionSource:null,client:null,capabilities:null,currentRender:null,batch:null,useCapturedTelemetry:false,controlDefaults:{},snapshots:{A:null,B:null},referenceAxisX:'depth',referenceAxisY:'hardness',referenceSelected:null,referencePoints:[],previewFingerprint:null};
const primaryRangeControls=['energy','depth','texture','attack','ring','boominess','brightness','warmth','space'];
const rangeControls=['size','roughness','hardness','transient','body','residual','damping','style-amount','covariance'];
const controlIds=['material',...primaryRangeControls,'object','size','roughness','hardness','transient','body','residual','damping','style','style-amount','variants','covariance','source'];
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
const close=(a,b,epsilon=.0001)=>Math.abs(Number(a)-Number(b))<=epsilon;
const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,Number(value)));

function audioContext(){if(!state.audio)state.audio=new (window.AudioContext||window.webkitAudioContext)();$('sl-browser-rate').textContent=`${state.audio.sampleRate} Hz AudioContext`;return state.audio;}
function fmtHash(value=''){return value?value.slice(0,10):'—';}
function fmtRate(value){const rate=Number(value||0);return rate>=1000?`${(rate/1000).toLocaleString(undefined,{maximumFractionDigits:2})} kHz`:`${rate} Hz`;}
function fmtEncoding(value=''){const encoding=String(value||'').toLowerCase();if(encoding==='u8')return 'PCM8 unsigned';if(encoding==='pcm16')return 'PCM16';return encoding?encoding.toUpperCase():'source';}
function samplesOf(buffer){return buffer?.getChannelData?buffer.getChannelData(0):buffer?.samples||new Float32Array();}
function metrics(samples,sampleRate){let peak=0,last=-1;for(let i=0;i<samples.length;i++){const a=Math.abs(samples[i]);peak=Math.max(peak,a);if(a>.008)last=i;}return{peak,duration:last>=0?(last+1)*1000/sampleRate:0};}
function drawWaveform(samples){const canvas=$('sl-waveform'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#29313b';ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();if(!samples?.length)return;ctx.strokeStyle='#e4ad55';ctx.lineWidth=1;ctx.beginPath();const bucket=Math.max(1,Math.floor(samples.length/w));for(let x=0;x<w;x++){let lo=1,hi=-1;const start=x*bucket,end=Math.min(samples.length,start+bucket);for(let i=start;i<end;i++){lo=Math.min(lo,samples[i]);hi=Math.max(hi,samples[i]);}ctx.moveTo(x,(1-hi)*h/2);ctx.lineTo(x,(1-lo)*h/2);}ctx.stroke();}
function profileCaption(profile){return({preview:'Current browser preview','current-master':'Current canonical master','current-runtime':'Current runtime derivative',master:'Frozen promoted master',runtime:'Frozen shipping derivative'})[profile]||profile;}
function referenceKey(row){return row?.kind==='source'?`source:${row.id}`:`promoted:${row?.binding}:${row?.variant}`;}
function referenceAxisLabel(axis){return({depth:'Depth',hardness:'Hardness',roughness:'Roughness',boominess:'Boominess',brightness:'Brightness',warmth:'Warmth',ring:'Ring',reverberance:'Reverberance'})[axis]||axis;}
function referenceCandidate(){const key=state.referenceSelected;return referenceLibrary(state.manifest).find(row=>referenceKey(row)===key)||null;}
function referenceDeltaText(candidate,current=state.previewFingerprint){
  if(!candidate?.fingerprint||!current)return 'Choose a reference to compare its sound color.';
  const ranked=PERCEPTUAL_FINGERPRINT_AXES.map(axis=>({axis,delta:Number(candidate.fingerprint[axis]||0)-Number(current[axis]||0)})).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,3);
  return ranked.map(row=>`${referenceAxisLabel(row.axis)} ${row.delta>=0?'+':''}${row.delta.toFixed(2)}`).join(' · ');
}
function selectReference(row){
  state.referenceSelected=row?referenceKey(row):null;const selected=referenceCandidate();$('sl-reference-title').textContent=selected?.label||'Choose a promoted sound or imported reference';$('sl-reference-delta').textContent=selected?referenceDeltaText(selected):'Nearest approved sounds update with the current draft.';$('sl-reference-play').disabled=!selected||selected.kind!=='promoted';$('sl-reference-match').disabled=!selected;document.querySelectorAll('.reference-nearest button').forEach(button=>button.classList.toggle('active',button.dataset.referenceKey===state.referenceSelected));drawReferenceMap();
}
function drawReferenceMap(){
  const canvas=$('sl-reference-map');if(!canvas||!state.manifest)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,pad=34,xAxis=state.referenceAxisX,yAxis=state.referenceAxisY,rows=referenceLibrary(state.manifest);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1015';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#25303a';ctx.lineWidth=1;for(let i=0;i<=4;i++){const x=pad+(w-pad*2)*i/4,y=pad+(h-pad*2)*i/4;ctx.beginPath();ctx.moveTo(x,pad);ctx.lineTo(x,h-pad);ctx.stroke();ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke();}ctx.fillStyle='#758290';ctx.font='12px ui-monospace, SFMono-Regular, Menlo, monospace';ctx.fillText(referenceAxisLabel(xAxis),w-pad-ctx.measureText(referenceAxisLabel(xAxis)).width,h-9);ctx.save();ctx.translate(12,pad+ctx.measureText(referenceAxisLabel(yAxis)).width);ctx.rotate(-Math.PI/2);ctx.fillText(referenceAxisLabel(yAxis),0,0);ctx.restore();
  const points=[];for(const row of rows){const x=pad+clamp(row.fingerprint?.[xAxis])*(w-pad*2),y=h-pad-clamp(row.fingerprint?.[yAxis])*(h-pad*2),selected=referenceKey(row)===state.referenceSelected;ctx.beginPath();ctx.arc(x,y,selected?6:4,0,Math.PI*2);ctx.fillStyle=row.kind==='source'?'#87a6c5':'#78838f';ctx.fill();if(selected){ctx.strokeStyle='#e4ad55';ctx.lineWidth=2;ctx.stroke();}points.push({row,x,y});}
  if(state.previewFingerprint){const x=pad+clamp(state.previewFingerprint[xAxis])*(w-pad*2),y=h-pad-clamp(state.previewFingerprint[yAxis])*(h-pad*2);ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fillStyle='#e4ad55';ctx.fill();ctx.strokeStyle='#fff1d2';ctx.lineWidth=1;ctx.stroke();}state.referencePoints=points;
}
function renderReferenceExplorer(){
  if(!state.preview||!$('sl-reference-map'))return;state.previewFingerprint=perceptualFingerprint(samplesOf(state.preview),Number(state.preview.sampleRate||48000));$('sl-reference-current').textContent=`Draft · ${referenceAxisLabel(state.referenceAxisX)} ${state.previewFingerprint[state.referenceAxisX].toFixed(2)} · ${referenceAxisLabel(state.referenceAxisY)} ${state.previewFingerprint[state.referenceAxisY].toFixed(2)}`;
  const nearest=referenceLibrary(state.manifest).filter(row=>row.kind==='source'||row.binding!==state.binding?.id).map(row=>({...row,distance:fingerprintDistance(state.previewFingerprint,row.fingerprint)})).sort((a,b)=>a.distance-b.distance).slice(0,6);$('sl-reference-nearest').replaceChildren(...nearest.map(row=>{const button=document.createElement('button');button.dataset.referenceKey=referenceKey(row);button.classList.toggle('active',button.dataset.referenceKey===state.referenceSelected);button.innerHTML=`<span>${row.label}</span><small>distance ${row.distance.toFixed(3)}</small>`;button.addEventListener('click',()=>selectReference(row));return button;}));const selected=referenceCandidate();if(selected)$('sl-reference-delta').textContent=referenceDeltaText(selected);drawReferenceMap();
}
async function playReference(){const row=referenceCandidate();if(!row||row.kind!=='promoted')return;playAudition(await decodeUrl(`reference:${row.sha256}`,new URL(row.file,state.manifestUrl)));}
function matchReference(){
  const row=referenceCandidate();if(!row?.fingerprint||!state.previewFingerprint)return;const controls={depth:'depth',hardness:'attack',roughness:'texture',boominess:'boominess',brightness:'brightness',warmth:'warmth',ring:'ring',reverberance:'space'},applied=[];for(const [axis,id] of Object.entries(controls)){const delta=Number(row.fingerprint[axis])-Number(state.previewFingerprint[axis]),current=numeric(`sl-${id}`),next=clamp(current+delta);setRange(`sl-${id}`,Number(next.toFixed(2)));if(Math.abs(delta)>=.015)applied.push(`${referenceAxisLabel(axis)} ${delta>=0?'+':''}${delta.toFixed(2)}`);}updateChangedState();renderPreview();$('sl-reference-delta').textContent=applied.length?`Applied semantic delta · ${applied.slice(0,4).join(' · ')}`:'Current draft already matches this reference closely.';
}
function installReferenceMap(){
  const x=$('sl-reference-axis-x'),y=$('sl-reference-axis-y'),options=PERCEPTUAL_FINGERPRINT_AXES.map(axis=>new Option(referenceAxisLabel(axis),axis));x.replaceChildren(...options.map(o=>o.cloneNode(true)));y.replaceChildren(...options.map(o=>o.cloneNode(true)));x.value=state.referenceAxisX;y.value=state.referenceAxisY;const update=()=>{state.referenceAxisX=x.value;state.referenceAxisY=y.value;renderReferenceExplorer();};x.addEventListener('change',update);y.addEventListener('change',update);$('sl-reference-map').addEventListener('click',event=>{const canvas=event.currentTarget,rect=canvas.getBoundingClientRect(),sx=canvas.width/Math.max(1,rect.width),sy=canvas.height/Math.max(1,rect.height),px=(event.clientX-rect.left)*sx,py=(event.clientY-rect.top)*sy;let best=null,bestDistance=Infinity;for(const point of state.referencePoints){const d=Math.hypot(point.x-px,point.y-py);if(d<bestDistance){bestDistance=d;best=point.row;}}if(best&&bestDistance<=18*Math.max(sx,sy))selectReference(best);});$('sl-reference-play').addEventListener('click',()=>playReference().catch(error=>serviceState(error.message,'bad')));$('sl-reference-match').addEventListener('click',matchReference);
}
function showAudio(render,{hash='',profile='preview',sourceSampleRate=null,encoding=''}={}){const samples=samplesOf(render),playbackRate=Number(render.sampleRate||48000),sourceRate=Number(sourceSampleRate||playbackRate);drawWaveform(samples);const m=metrics(samples,playbackRate);$('sl-metric-duration').textContent=`${m.duration.toFixed(1)} ms`;$('sl-metric-peak').textContent=`peak ${m.peak.toFixed(3)}`;$('sl-metric-rate').textContent=profile==='preview'?`${fmtRate(sourceRate)} preview`:`${fmtRate(sourceRate)} · ${fmtEncoding(encoding)} source`;$('sl-metric-hash').textContent=profile==='preview'?'non-authoritative':`sha ${fmtHash(hash)}`;$('sl-waveform-caption').textContent=profileCaption(profile);state.displayProfile=profile;document.querySelectorAll('[data-profile]').forEach(b=>b.classList.toggle('active',b.dataset.profile===profile));}
function playBuffer(buffer){const ctx=audioContext(),source=ctx.createBufferSource();source.buffer=buffer;source.connect(ctx.destination);source.start();return source;}
function stopAudition(){if(!state.auditionSource)return;try{state.auditionSource.stop();}catch{}state.auditionSource=null;}
function playAudition(buffer){stopAudition();const source=playBuffer(buffer);state.auditionSource=source;source.onended=()=>{if(state.auditionSource===source)state.auditionSource=null;};return source;}
function stopSceneDraft(){if(!state.sceneDraftSource)return;try{state.sceneDraftSource.stop();}catch{}state.sceneDraftSource=null;}
function handleSceneReplay(event){if(!event)return;if(event.phase==='start'){stopSceneDraft();stopAudition();return;}if(event.phase==='proof'&&event.draft){const render=state.preview||renderPreview();state.sceneDraftSource=playBuffer(audioBufferFrom(audioContext(),render));return;}if(event.phase==='end')stopSceneDraft();}
function selectedMaterial(){return $('sl-material').value||state.binding.surface;}
function selectedVariant(){return Number($('sl-variant').value||0);}
function selectedObject(){return $('sl-object-profile').value||state.binding.object;}
function selectedStyle(){return $('sl-style-profile').value||state.binding.style;}
function rawResource(kind,id){return state.manifest.previewModel?.resources?.[kind]?.[id];}
function profileResources(){const binding={...state.binding,object:selectedObject(),style:selectedStyle(),surface:selectedMaterial()};return resolvePreviewResources(state.manifest,binding,selectedMaterial(),{object:selectedObject(),style:selectedStyle()});}

function currentPerceptualDescription(){return perceptualSoundDescription({energy:numeric('sl-energy'),depth:numeric('sl-depth'),texture:numeric('sl-texture'),attack:numeric('sl-attack'),ring:numeric('sl-ring'),boominess:numeric('sl-boominess'),brightness:numeric('sl-brightness'),warmth:numeric('sl-warmth'),space:numeric('sl-space')});}
function perceptualMapping(){return state.manifest.previewModel?.perceptualMapping||{};}
function authoringOverrides(){
  const base=profileResources(),defaults=state.controlDefaults,overrides=clone(state.binding.overrides||{});
  const ensure=(kind,key,value)=>{overrides[kind]??={};let cursor=overrides[kind],parts=key.split('.');for(const part of parts.slice(0,-1))cursor=cursor[part]??={};cursor[parts.at(-1)]=value;};
  const size=numeric('sl-size'),damping=numeric('sl-damping'),covariance=numeric('sl-covariance');
  if(!close(size,defaults.size)||!close(damping,defaults.damping)){
    const modal=base.object.modal||{},root=Math.sqrt(size/Number(defaults.size||1)),damp=damping/Number(defaults.damping||1);
    ensure('object','modal.frequencyScale',Number(modal.frequencyScale??1)/root);
    ensure('object','modal.decayScale',Number(modal.decayScale??1)*root*damp);
    ensure('object','modal.coupling',Number(modal.coupling??1)*(0.85+0.15*size));
  }
  if(!close(covariance,defaults.covariance)){
    const factor=covariance/Number(defaults.covariance||1),v=base.object.variation||{};
    ensure('object','variation.frequency',Number(v.frequency??.018)*factor);ensure('object','variation.decay',Number(v.decay??.08)*factor);ensure('object','variation.brightness',Number(v.brightness??.035)*factor);
  }
  for(const [id,path] of [['roughness','contact.roughness'],['hardness','transient.hardness']])if(!close(numeric(`sl-${id}`),defaults[id]))ensure('material',path,numeric(`sl-${id}`));
  for(const id of ['transient','body','residual'])if(!close(numeric(`sl-${id}`),defaults[id]))ensure('recipe',`mix.${id}`,numeric(`sl-${id}`));
  const amount=numeric('sl-style-amount');if(!close(amount,defaults['style-amount'])){
    const f=base.style.finishing||{},ratio=amount/Number(defaults['style-amount']||1);
    ensure('style','finishing.drive',1+(Number(f.drive??1)-1)*ratio);ensure('style','finishing.softClip',Number(f.softClip??.75)*ratio);ensure('style','finishing.periodColoration',Number(f.periodColoration??0)*ratio);
  }
  const source=$('sl-source').value,defaultSource=String(defaults.source||'');if(source!==defaultSource)ensure('material','residual.source',source||null);
  return overrides;
}
function currentBinding(){return{...state.binding,surface:selectedMaterial(),object:selectedObject(),style:selectedStyle(),strength:strengthForEnergy(numeric('sl-energy'),perceptualMapping()),variants:Math.max(1,Math.min(16,Math.round(numeric('sl-variant-count')||1))),perceptual:currentPerceptualDescription(),overrides:authoringOverrides()};}
function currentResources(){const binding=currentBinding();return resolvePreviewResources(state.manifest,binding,binding.surface,{object:binding.object,style:binding.style});}
function currentSceneMotion(){return state.scene?sceneMotionSamples(state.scene,state.sceneWindow):[];}
function currentSceneIntent(binding=currentBinding()){return state.scene?sceneSoundIntent(state.manifest,binding,state.scene,state.sceneWindow,{object:binding.object,surface:binding.surface,recipe:binding.recipe}):null;}
function currentTrace(){
  if(!state.useCapturedTelemetry||!state.events.length)return null;
  const binding=currentBinding(),intent=currentSceneIntent(binding),motion=currentSceneMotion();
  return telemetryTrace(state.manifest.project,state.events,{binding:state.binding.id,...(intent?{sceneIntent:intent}:{}),...(motion.length?{motion}:{}),...(state.sceneWindow?{window:{startFrame:state.sceneWindow.startFrame,endFrame:state.sceneWindow.endFrame}}:{})});
}
function currentJob(){const binding=currentBinding(),trace=currentTrace();return{bindingId:binding.id,surface:binding.surface,object:binding.object,recipe:binding.recipe,style:binding.style,strength:binding.strength,variants:binding.variants,seed:Number($('sl-seed').value)>>>0,perceptual:binding.perceptual,overrides:binding.overrides,...(trace?{telemetryTrace:trace,useCapturedTelemetry:true}:{})};}

function renderPreview(){const binding=currentBinding(),{material,object,recipe,style,environment}=currentResources(),telemetry=currentTrace()||(state.useCapturedTelemetry?currentSceneMotion():[]),render=renderSoundPreview({sampleRate:Number(state.manifest.previewModel?.renderer?.sampleRate||48000),strength:binding.strength,seed:Number($('sl-seed').value)>>>0,material,object,recipe,style,environment,telemetry,binding});state.preview=render;showAudio(render,{profile:'preview',sourceSampleRate:render.sampleRate});updateChangedState();renderReferenceExplorer();return render;}
function outputRow(profile){return outputsFor(state.manifest,state.binding.id,profile).find(row=>row.variant===selectedVariant())||outputsFor(state.manifest,state.binding.id,profile)[0];}
async function decodeUrl(key,url){if(state.decoded.has(key))return state.decoded.get(key);const response=await fetch(new URL(url,document.baseURI),{cache:'no-store'});if(!response.ok)throw new Error(`audio load failed (${response.status})`);const buffer=await audioContext().decodeAudioData(await response.arrayBuffer());state.decoded.set(key,buffer);return buffer;}
async function decodedOutput(profile){const row=outputRow(profile);if(!row)throw new Error(`No ${profile} output for ${state.binding.id}`);const buffer=await decodeUrl(`promoted:${profile}:${row.variant}:${row.sha256}`,new URL(row.file,state.manifestUrl));return{buffer,row};}
function currentProfile(profile){const key=profile==='current-master'?'master':'runtime',row=state.currentRender?.profiles?.[key];if(!row)throw new Error('Render the current canonical sound first');return{key,row};}
async function showProfile(profile){
  if(profile==='preview'){if(!state.preview)renderPreview();showAudio(state.preview,{profile,sourceSampleRate:state.preview.sampleRate});return;}
  if(profile.startsWith('current-')){const {key,row}=currentProfile(profile),buffer=await decodeUrl(`current:${key}:${row.sha256}`,row.url);showAudio(buffer,{hash:row.sha256,profile,sourceSampleRate:row.sampleRate,encoding:row.encoding});return;}
  const {buffer,row}=await decodedOutput(profile);showAudio(buffer,{hash:row.sha256,profile,sourceSampleRate:row.sampleRate,encoding:row.encoding});
}
async function playProfile(profile){if(profile==='preview'){playAudition(audioBufferFrom(audioContext(),state.preview||renderPreview()));return;}if(profile.startsWith('current-')){const {key,row}=currentProfile(profile);playAudition(await decodeUrl(`current:${key}:${row.sha256}`,row.url));return;}const {buffer}=await decodedOutput(profile);playAudition(buffer);}

function syncCaseControls(){document.querySelectorAll('.case-button').forEach(b=>b.classList.toggle('active',b.dataset.id===state.binding.id));if($('sl-case-picker').value!==state.binding.id)$('sl-case-picker').value=state.binding.id;}
function optionNodes(rows,selected,label=row=>row.id.replaceAll('-',' ')){return rows.map(row=>new Option(label(row),row.id,row.id===selected,row.id===selected));}
function sourceNodes(selected){return [new Option('Procedural residual','',!selected,!selected),...sourceOptions(state.manifest).map(row=>new Option(`${row.id} · ${row.role}`,row.id,row.id===selected,row.id===selected))];}
function setRange(id,value){$(id).value=String(value);const out=$(`${id}-out`);if(out)out.textContent=Number(value).toFixed(2);}
function actionGenerator(){return String(rawResource('recipes',state.binding?.recipe)?.generator||'impact');}
function updateActionLabels(){const continuous=['roll','slide','scrape','mechanism','emitter'].includes(actionGenerator()),label=continuous?'Motion energy':actionGenerator()==='explosion'?'Blast energy':actionGenerator()==='launch'?'Launch energy':'Impact energy';$('sl-energy-label').textContent=label;$('sl-energy').setAttribute('aria-label',label);}
function setBinding(id){
  stopSceneDraft();stopAudition();if(state.runtime){state.runtime.stop?.();state.runtime=null;$('sl-start-native').disabled=false;}state.binding=bindingFor(state.manifest,id);syncCaseControls();state.currentRender=null;state.batch=null;state.decoded.clear();state.events=[];state.selectedEvent=-1;state.scene=null;state.sceneWindow=null;state.sceneReplayMode='native';state.useCapturedTelemetry=false;state.referenceSelected=null;$('sl-use-capture').setAttribute('aria-pressed','false');$('sl-scene-contact').hidden=true;
  $('sl-object').textContent=state.binding.object;$('sl-recipe').textContent=state.binding.recipe;$('sl-style').textContent=state.binding.style;$('sl-event').textContent=state.binding.event;
  updateActionLabels();
  $('sl-material').replaceChildren(...optionNodes(materialOptions(state.manifest),state.binding.surface));$('sl-object-profile').replaceChildren(...optionNodes(resourceOptions(state.manifest,'objects'),state.binding.object));$('sl-style-profile').replaceChildren(...optionNodes(resourceOptions(state.manifest,'styles'),state.binding.style));
  const base=profileResources(),master=outputsFor(state.manifest,state.binding.id,'master');$('sl-variant').replaceChildren(...master.map(row=>new Option(`variant ${row.variant+1} · seed ${row.seed}`,String(row.variant))));$('sl-seed').value=String(master[0]?.seed||1);$('sl-source').replaceChildren(...sourceNodes(base.material.residual?.source||''));
  const semantic=state.binding.perceptual||{};state.controlDefaults={material:state.binding.surface,energy:Number(semantic.energy??energyForStrength(Number(state.binding.strength??.7),perceptualMapping())),depth:Number(semantic.depth??.5),texture:Number(semantic.roughness??base.material.contact?.roughness??.5),attack:Number(semantic.hardness??base.material.transient?.hardness??.5),ring:Number(semantic.ring??.5),boominess:Number(semantic.boominess??base.recipe.perceptual?.boominess??.5),brightness:Number(semantic.brightness??base.recipe.perceptual?.brightness??.5),warmth:Number(semantic.warmth??base.recipe.perceptual?.warmth??.5),space:Number(semantic.reverberance??base.recipe.perceptual?.reverberance??0),object:state.binding.object,size:1,roughness:Number(base.material.contact?.roughness??.5),hardness:Number(base.material.transient?.hardness??.5),transient:Number(base.recipe.mix?.transient??.6),body:Number(base.recipe.mix?.body??.8),residual:Number(base.recipe.mix?.residual??.3),damping:1,style:state.binding.style,'style-amount':1,variants:Number(state.binding.variants||4),covariance:1,source:String(base.material.residual?.source||'')};
  for(const id of primaryRangeControls)setRange(`sl-${id}`,state.controlDefaults[id]);setRange('sl-size',1);setRange('sl-roughness',state.controlDefaults.roughness);setRange('sl-hardness',state.controlDefaults.hardness);setRange('sl-transient',state.controlDefaults.transient);setRange('sl-body',state.controlDefaults.body);setRange('sl-residual',state.controlDefaults.residual);setRange('sl-damping',1);setRange('sl-style-amount',1);setRange('sl-covariance',1);$('sl-variant-count').value=String(state.controlDefaults.variants);updateSourceMeta();loadSnapshots();state.preview=null;renderPreview();renderTimeline();updateCurrentButtons();$('sl-batch-strip').replaceChildren();
}
function populateCases(){const rows=state.manifest.bindings;$('sl-case-list').replaceChildren(...rows.map(binding=>{const b=document.createElement('button');b.className='case-button';b.dataset.id=binding.id;b.innerHTML=`<strong>${binding.event}</strong><small>${binding.match?.actorFamily||binding.id} · ${binding.surface}</small>`;b.addEventListener('click',()=>setBinding(binding.id));return b;}));$('sl-case-picker').replaceChildren(...rows.map(binding=>new Option(binding.event,binding.id)));$('sl-case-count').textContent=`${rows.length}`;}

function controlValue(id){if(id==='material')return selectedMaterial();if(primaryRangeControls.includes(id))return numeric(`sl-${id}`);if(id==='object')return selectedObject();if(id==='style')return selectedStyle();if(id==='variants')return numeric('sl-variant-count');if(id==='source')return $('sl-source').value;return numeric(`sl-${id}`);}
function changed(id){const a=controlValue(id),b=state.controlDefaults[id];return typeof a==='number'&&!Number.isNaN(a)?!close(a,b):String(a)!==String(b??'');}
function soundColorSummary(){
  if(!state.binding)return '';
  const object=(state.binding.match?.actorFamily||state.binding.object||'object').replace(/^sm\d+-/,'').replaceAll('-',' ');
  const depth=numeric('sl-depth'),texture=numeric('sl-texture'),attack=numeric('sl-attack'),ring=numeric('sl-ring'),boom=numeric('sl-boominess'),brightness=numeric('sl-brightness'),warmth=numeric('sl-warmth'),space=numeric('sl-space');
  const depthLabel=depth>.68?'heavy · deep':depth<.34?'light · thin':'solid';
  const textureLabel=texture>.68?'rocky':texture<.34?'smooth':'textured';
  const attackLabel=attack>.68?'hard attack':attack<.34?'soft attack':'clear attack';
  const ringLabel=ring>.7?'ringing tail':ring<.32?'short · dead tail':'short-to-medium ring';
  const tone=[boom>.68?'boomy':boom<.34?'tight':null,brightness>.68?'bright':brightness<.34?'dark':null,warmth>.68?'warm':warmth<.34?'cold':null,space>.55?'roomy':space>.15?'slightly roomy':'dry'].filter(Boolean).join(' · ');
  const surface=selectedMaterial().replaceAll('-',' '),relation=({roll:'rolling on',slide:'sliding on',scrape:'scraping across',mechanism:'moving against',emitter:'venting through',launch:'launching from',explosion:'exploding against'}[actionGenerator()]||'hitting');
  return `${object} ${relation} ${surface} — ${depthLabel}, ${textureLabel}, ${attackLabel}, ${ringLabel}${tone?`, ${tone}`:''}.`;
}
function updateSoundSummary(){const node=$('sl-sound-summary');if(node)node.textContent=soundColorSummary();}
function updateChangedState(){let count=0;for(const id of controlIds){const row=document.querySelector(`[data-control="${id}"]`);if(!row)continue;const yes=changed(id);row.classList.toggle('changed',yes);if(yes)count+=1;}$('sl-changed-count').textContent=count?`${count} changed`:'profile defaults';$('sl-object').textContent=selectedObject();$('sl-style').textContent=selectedStyle();updateSourceMeta();updateSoundSummary();}
function resetControl(id){const value=state.controlDefaults[id];if(id==='material')$('sl-material').value=value;else if(primaryRangeControls.includes(id))setRange(`sl-${id}`,value);else if(id==='object')$('sl-object-profile').value=value;else if(id==='style')$('sl-style-profile').value=value;else if(id==='variants')$('sl-variant-count').value=value;else if(id==='source')$('sl-source').value=value;else setRange(`sl-${id}`,value);renderPreview();}
function snapshotValues(){return Object.fromEntries(controlIds.map(id=>[id,controlValue(id)]));}
function applySnapshot(values){if(!values)return;for(const [id,value] of Object.entries(values)){if(id==='material')$('sl-material').value=value;else if(primaryRangeControls.includes(id))setRange(`sl-${id}`,value);else if(id==='object')$('sl-object-profile').value=value;else if(id==='style')$('sl-style-profile').value=value;else if(id==='variants')$('sl-variant-count').value=value;else if(id==='source')$('sl-source').value=value;else if(document.getElementById(`sl-${id}`))setRange(`sl-${id}`,value);}renderPreview();}
function snapshotKey(){return `soundlab:snapshots:${state.manifest.project}:${state.binding.id}`;}
function loadSnapshots(){try{state.snapshots={A:null,B:null,...JSON.parse(localStorage.getItem(snapshotKey())||'{}')};}catch{state.snapshots={A:null,B:null};}}
function saveSnapshot(slot){state.snapshots[slot]=snapshotValues();localStorage.setItem(snapshotKey(),JSON.stringify(state.snapshots));$('sl-promotion-state').textContent=`Stored parameter snapshot ${slot}.`;}


function applySoundDescription(){
  const values=Object.fromEntries(primaryRangeControls.map(id=>[id,numeric(`sl-${id}`)]));
  const result=interpretSoundDescription($('sl-description').value,{values,scene:state.scene});
  for(const change of result.changes){if(change.type==='control'&&primaryRangeControls.includes(change.axis))setRange(`sl-${change.axis}`,change.value);}
  if(result.timing&&state.scene&&state.sceneWindow){
    if(Number.isFinite(result.timing.startFrame))state.sceneWindow.startFrame=Math.max(state.scene.minFrame,Math.min(state.scene.proofFrame,result.timing.startFrame));
    if(Number.isFinite(result.timing.endFrame))state.sceneWindow.endFrame=Math.min(state.scene.maxFrame,Math.max(state.scene.proofFrame,result.timing.endFrame));
    if(state.sceneWindow.endFrame<=state.sceneWindow.startFrame)state.sceneWindow.endFrame=Math.min(state.scene.maxFrame,state.sceneWindow.startFrame+1);
    renderSceneWindow();
  }
  renderPreview();
  const applied=result.changes.map(change=>change.type==='control'?`${change.axis} ${Number(change.value).toFixed(2)}`:`${change.edge} ${change.frame}f`);
  $('sl-description-result').textContent=applied.length?`Applied: ${applied.join(' · ')}${result.notes.length?` · ${result.notes.join(' ')}`:''}`:result.notes.join(' ')||'No changes applied.';
  if(result.timing)replaySelectedEvent();
}

function updateSourceMeta(){const id=$('sl-source')?.value,row=sourceOptions(state.manifest).find(item=>item.id===id);$('sl-source-meta').textContent=row?`${row.id} · ${row.role} · onset ${row.onsetSample||0} · sha ${fmtHash(row.sha256)} · ${row.provenance?.provider||'unknown provider'}${row.provenance?.model?` / ${row.provenance.model}`:''}`:'No frozen source selected; procedural residual is used.';}
function renderTimeline(){
  const event=state.events[state.selectedEvent]||state.events.at(-1);
  if(!event){$('sl-event-readout').textContent='No captured event';$('sl-replay-context').disabled=true;$('sl-replay-draft').disabled=true;$('sl-event-marker').style.opacity='.2';return;}
  $('sl-event-readout').textContent=`${event.event} · tick ${event.tick} · Δ ${(event.frameDelta||[]).join(',')}`;
  $('sl-telemetry').textContent=JSON.stringify(event,null,2);
  const replayable=!!state.runtime?.canReplayEvent?.(event.serial);$('sl-replay-context').disabled=!replayable;$('sl-replay-draft').disabled=!replayable;
}
function showEvent(event){state.events.push(event);state.selectedEvent=state.events.length-1;renderTimeline();}
function scenePercent(frame,scene=state.scene){if(!scene)return 0;return 100*(Number(frame)-scene.minFrame)/Math.max(1,scene.maxFrame-scene.minFrame);}
function renderSceneWindow(){
  const scene=state.scene,windowState=state.sceneWindow;if(!scene||!windowState){$('sl-scene-window-readout').textContent='Waiting for scene';return;}
  const start=clamp(scenePercent(windowState.startFrame),0,100),end=clamp(scenePercent(windowState.endFrame),0,100),proof=clamp(scenePercent(scene.proofFrame),0,100);
  $('sl-scene-start').style.left=`${start}%`;$('sl-scene-end').style.left=`${end}%`;$('sl-event-marker').style.left=`${proof}%`;$('sl-event-marker').style.opacity='1';
  $('sl-scene-selection').style.left=`${start}%`;$('sl-scene-selection').style.width=`${Math.max(0,end-start)}%`;
  $('sl-scene-window-readout').textContent=`${windowState.startFrame}–${windowState.endFrame}f · contact ${scene.proofFrame}f`;
  renderSceneOverlay();
}
function scenePointAt(frame,scene=state.scene){if(!scene?.path?.length)return null;return scene.path.reduce((best,row)=>!best||Math.abs(row.frameSerial-frame)<Math.abs(best.frameSerial-frame)?row:best,null);}
function drawSceneMarker(ctx,row,sx,sy,label,direction=1){if(!row)return;const x=row.x*sx,y=row.y*sy;ctx.save();ctx.strokeStyle='#f3d28c';ctx.fillStyle='#0d1014';ctx.lineWidth=2;ctx.beginPath();ctx.rect(x-4,y-4,8,8);ctx.fill();ctx.stroke();ctx.font='bold 9px ui-monospace,monospace';ctx.textBaseline='middle';ctx.fillStyle='#f3d28c';ctx.fillText(label,x+7*direction,y);ctx.restore();}
function renderSceneOverlay(){
  const canvas=$('sl-scene-overlay'),ctx=canvas?.getContext('2d'),scene=state.scene;if(!ctx||!scene){return;}ctx.clearRect(0,0,canvas.width,canvas.height);
  const viewport=scene.viewport||{width:320,height:200},sx=canvas.width/viewport.width,sy=canvas.height/viewport.height,path=scene.path||[],windowState=state.sceneWindow||scene;
  const drawPath=(rows,alpha,width,dash=[])=>{if(rows.length<2)return;ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle='#e4ad55';ctx.lineWidth=width;ctx.lineJoin='round';ctx.lineCap='round';ctx.setLineDash(dash);ctx.beginPath();rows.forEach((row,index)=>{const x=row.x*sx,y=row.y*sy;if(index)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.stroke();ctx.restore();};
  drawPath(path,.24,2);
  const selected=path.filter(row=>row.frameSerial>=windowState.startFrame&&row.frameSerial<=windowState.endFrame);drawPath(selected,.98,3);
  const rebound=scene.segments?.find(row=>row.id==='rebound');if(rebound)drawPath(path.filter(row=>row.frameSerial>=rebound.startFrame&&row.frameSerial<=rebound.endFrame),.95,3,[7,5]);
  const before=path.filter(row=>row.frameSerial<scene.proofFrame).at(-1),contact=scene.contact;if(before&&contact){const dx=contact.x-before.x,dy=contact.y-before.y,m=Math.hypot(dx,dy);if(m>.5){const scale=Math.min(18,Math.max(8,m*3))/m,x1=contact.x*sx,y1=contact.y*sy,x0=(contact.x-dx*scale)*sx,y0=(contact.y-dy*scale)*sy,angle=Math.atan2(y1-y0,x1-x0);ctx.save();ctx.strokeStyle='#f3d28c';ctx.globalAlpha=.8;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x1,y1);ctx.lineTo(x1-Math.cos(angle-.55)*7,y1-Math.sin(angle-.55)*7);ctx.moveTo(x1,y1);ctx.lineTo(x1-Math.cos(angle+.55)*7,y1-Math.sin(angle+.55)*7);ctx.stroke();ctx.restore();}}
  drawSceneMarker(ctx,scenePointAt(windowState.startFrame),sx,sy,'S',1);drawSceneMarker(ctx,scenePointAt(windowState.endFrame),sx,sy,'E',-1);
  const marker=$('sl-scene-contact');if(contact&&marker){marker.hidden=false;marker.style.left=`${100*contact.x/viewport.width}%`;marker.style.top=`${100*contact.y/viewport.height}%`;}
}
function selectSceneContact(){if(!state.scene)return;const index=state.events.findIndex(event=>Number(event.serial)===Number(state.scene.serial));if(index>=0){state.selectedEvent=index;renderTimeline();}$('sl-native-canvas').focus();}
function showScene(scene){
  state.scene={...scene,viewport:scene.viewport||{width:320,height:200}};state.sceneWindow={startFrame:scene.startFrame,endFrame:scene.endFrame};state.useCapturedTelemetry=true;$('sl-use-capture').setAttribute('aria-pressed','true');
  const label=(state.binding.match?.actorFamily||state.binding.object||'object').replace(/^sm\d+-/,'').replaceAll('-',' '),surface=selectedMaterial().replaceAll('-',' '),action=String(rawResource('recipes',state.binding.recipe)?.generator||'impact').replaceAll('-',' ');
  $('sl-scene-title').textContent=`${label} → ${surface} · ${action}`;
  const facts=scene.facts||{};$('sl-scene-motion').textContent=`fall ${facts.fallPx||0}px · horizontal ${facts.horizontalPx||0}px · contact ${scene.proofFrame}f · bounce ${facts.bouncePx||0}px${facts.bounceCount?` ×${facts.bounceCount}`:''}`;
  const segments=scene.segments||[];$('sl-scene-script').textContent=segments.length?segments.map(row=>`${row.label} ${Math.max(1,row.endFrame-row.startFrame+1)}f`).join(' → '):'contact anchored to the native semantic event';
  renderSceneWindow();renderTimeline();renderPreview();
}
function downloadJson(name,value){const url=URL.createObjectURL(new Blob([`${JSON.stringify(value,null,2)}\n`],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
function setNativeCollapsed(collapsed){const panel=$('sl-native-panel');panel.dataset.collapsed=String(collapsed);$('sl-toggle-native').textContent=collapsed?'Show':'Hide';$('sl-toggle-native').setAttribute('aria-expanded',String(!collapsed));}
function nativeSceneAuthoringOptions(){const recipe=state.manifest.previewModel?.resources?.recipes?.[state.binding.recipe]||{};return{submap:state.binding.match?.submap||0,event:state.binding.event,match:state.binding.match||{},action:recipe.generator||'impact',playback:recipe.playback?.kind||'',durationMs:Number(recipe.durationMs||0)};}
function nativeInputConfig(){return state.manifest?.authoring?.nativeInput||null;}
function showNativeInput(info={}){const config=nativeInputConfig(),setup=$('sl-native-setup');if(!config||!setup)return;setup.hidden=false;$('sl-native-input-title').textContent=info.name?`${config.label} · ${info.name}`:config.label;$('sl-native-input-status').textContent=info.status==='ready'?(info.remembered?'Ready · remembered in this browser':`Ready · ${String(info.source||'loaded').replaceAll('-',' ')}`):(info.message||config.help||'Choose the required native input.');$('sl-native-input-button-label').textContent=info.status==='ready'?`Replace ${config.label}`:config.buttonLabel||`Load ${config.label}`;}
function configureNativeInput(){const config=nativeInputConfig(),setup=$('sl-native-setup'),input=$('sl-native-input-file');if(!setup||!input)return;setup.hidden=!config;if(!config)return;input.accept=config.accept||'';showNativeInput();}
async function ensureNativeRuntime(){if(state.runtime)return state.runtime;const adapterPath=state.manifest.authoring?.nativeAdapter;if(!adapterPath)throw new Error(`Project ${state.manifest.project} does not provide a native preview adapter`);const module=await import(new URL(adapterPath,state.manifestUrl)),SoundLabRuntime=module.SoundLabRuntime||module.default;if(typeof SoundLabRuntime!=='function')throw new Error(`Native adapter ${adapterPath} must export SoundLabRuntime or default`);state.runtime=new SoundLabRuntime({canvas:$('sl-native-canvas'),onEvent:showEvent,onScene:showScene,onFrame:()=>renderSceneOverlay(),onReplay:handleSceneReplay,onStatus:text=>$('sl-native-status').textContent=text,onNativeInput:showNativeInput});return state.runtime;}
function handleNativeError(error){$('sl-native-status').textContent=error?.message||String(error);if(error?.code==='SOUNDLAB_NATIVE_INPUT_REQUIRED')showNativeInput({message:error.message});}
async function startNative(){if(state.capabilities?.capabilities?.nativePreview===false)throw new Error(state.capabilities.nativePreviewReason||'Native preview runtime is unavailable.');setNativeCollapsed(false);const runtime=await ensureNativeRuntime();await runtime.start(nativeSceneAuthoringOptions());$('sl-start-native').disabled=true;$('sl-native-canvas').focus();}
async function loadNativeInput(file){if(!file)return;const runtime=await ensureNativeRuntime();if(typeof runtime.loadNativeInput!=='function')throw new Error('This native preview adapter does not accept a local input file.');$('sl-native-status').textContent=`Loading ${file.name||nativeInputConfig()?.label||'native input'}…`;await runtime.loadNativeInput(file);if(state.capabilities?.capabilities?.nativePreview===false){$('sl-native-status').textContent=state.capabilities.nativePreviewReason||'ROM ready; native preview runtime is unavailable.';return;}await startNative();}
async function replaySelectedEvent(mode=state.sceneReplayMode){const event=state.events[state.selectedEvent];if(!event||!state.runtime)return;state.sceneReplayMode=mode==='draft'?'draft':'native';stopSceneDraft();stopAudition();const options={suppressSoundLab:state.sceneReplayMode==='draft'};const ok=state.scene&&Number(state.scene.serial)===Number(event.serial)?state.runtime.replayScene?.(event.serial,state.sceneWindow,options):state.runtime.replayEvent?.(event.serial);if(!ok)return;$('sl-native-canvas').focus();}

function rangeValueAt(input,surface,clientX){const rect=surface.getBoundingClientRect(),min=Number(input.min||0),max=Number(input.max||1),step=Number(input.step||.01),ratio=Math.max(0,Math.min(1,(clientX-rect.left)/Math.max(1,rect.width))),raw=min+(max-min)*ratio,steps=Math.round((raw-min)/step);return Math.max(min,Math.min(max,min+steps*step));}
function installPointerRange(id){const surface=$(`sl-${id}-surface`),input=$(`sl-${id}`);if(!surface||!input)return;let active=null;const update=event=>{input.value=String(rangeValueAt(input,surface,event.clientX));input.dispatchEvent(new Event('input',{bubbles:true}));};surface.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;active=event.pointerId;surface.setPointerCapture?.(active);input.focus({preventScroll:true});update(event);event.preventDefault();});surface.addEventListener('pointermove',event=>{if(event.pointerId!==active)return;update(event);event.preventDefault();});const finish=event=>{if(event.pointerId!==active)return;update(event);if(surface.hasPointerCapture?.(active))surface.releasePointerCapture(active);active=null;renderPreview();event.preventDefault();};surface.addEventListener('pointerup',finish);surface.addEventListener('pointercancel',event=>{if(event.pointerId!==active)return;if(surface.hasPointerCapture?.(active))surface.releasePointerCapture(active);active=null;});}
function installSceneWindow(){
  const track=$('sl-scene-window');
  for(const [id,key] of [['sl-scene-start','startFrame'],['sl-scene-end','endFrame']]){const handle=$(id);let active=null;const update=event=>{if(!state.scene||!state.sceneWindow)return;const rect=track.getBoundingClientRect(),ratio=clamp((event.clientX-rect.left)/Math.max(1,rect.width)),raw=Math.round(state.scene.minFrame+ratio*(state.scene.maxFrame-state.scene.minFrame));state.sceneWindow[key]=key==='startFrame'?Math.min(state.scene.proofFrame,Math.min(raw,state.sceneWindow.endFrame-1)):Math.max(state.scene.proofFrame,Math.max(raw,state.sceneWindow.startFrame+1));renderSceneWindow();};handle.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;active=event.pointerId;handle.setPointerCapture?.(active);update(event);event.preventDefault();});handle.addEventListener('pointermove',event=>{if(event.pointerId===active){update(event);event.preventDefault();}});const finish=event=>{if(event.pointerId!==active)return;update(event);if(handle.hasPointerCapture?.(active))handle.releasePointerCapture(active);active=null;renderPreview();replaySelectedEvent();event.preventDefault();};handle.addEventListener('pointerup',finish);handle.addEventListener('pointercancel',()=>{active=null;});}
}
function installPersistedDetails(){document.querySelectorAll('details[data-persist-key]').forEach(details=>{const key=`soundlab:open:${details.dataset.persistKey}`;try{const stored=localStorage.getItem(key);if(stored!==null)details.open=stored==='1';}catch{}details.addEventListener('toggle',()=>{try{localStorage.setItem(key,details.open?'1':'0');}catch{}});});}

function updateCurrentButtons(){const enabled=!!state.currentRender;for(const profile of ['current-master','current-runtime'])document.querySelector(`[data-profile="${profile}"]`).disabled=!enabled;}
function serviceState(text,kind=''){$('sl-promotion-state').textContent=text;$('sl-promotion-state').className=`promotion-state ${kind}`.trim();}
function setServiceEnabled(enabled){for(const id of ['sl-render-canonical','sl-render-variants','sl-render-materials','sl-render-sweep','sl-promote','sl-import-source'])$(id).disabled=!enabled;$('sl-canonical-panel').hidden=!enabled;}
async function connectAuthoringService(base){if(!base){state.client=null;state.capabilities=null;setServiceEnabled(false);return;}state.client=new SoundLabAuthoringClient(base);try{state.capabilities=await state.client.connect();if(!state.capabilities?.connected)throw new Error('SoundLab authoring service unavailable');setServiceEnabled(true);$('sl-authoring-mode').textContent='connected authoring';$('sl-authoring-mode').className='sl-pill';$('sl-author-mode-caption').textContent='preview + canonical';$('sl-service-detail').textContent='Canonical renderer and promotion are connected to this development host.';if(state.capabilities.capabilities?.nativePreview===false){$('sl-native-status').textContent=state.capabilities.nativePreviewReason||'Native preview package is unavailable.';$('sl-start-native').disabled=true;}$('sl-canonical-state').textContent=state.capabilities.build.ok?'current':'stale';$('sl-build-state').textContent=state.capabilities.build.ok?`${state.capabilities.build.outputs} promoted outputs`:'promoted outputs stale';$('sl-build-state').classList.toggle('stale',!state.capabilities.build.ok);serviceState(state.capabilities.build.ok?'Canonical build is current.':state.capabilities.build.problems[0]||'Canonical build is stale.',state.capabilities.build.ok?'good':'bad');const sources=await state.client.sources();state.manifest.previewModel.sources=sources.sources;const selected=$('sl-source').value;$('sl-source').replaceChildren(...sourceNodes(selected));updateSourceMeta();renderReferenceExplorer();}catch{state.client=null;state.capabilities=null;setServiceEnabled(false);}}
async function renderCanonical(){if(!state.client)return;serviceState('Rendering current canonical master + runtime…');const result=await state.client.render(currentJob());state.currentRender=result;state.decoded.clear();updateCurrentButtons();serviceState(`Current canonical ready · master ${fmtHash(result.profiles.master.sha256)} · runtime ${fmtHash(result.profiles.runtime.sha256)}`,'good');await showProfile('current-master');}
function renderBatchStrip(result){state.batch=result;$('sl-batch-strip').replaceChildren(...result.rows.map(row=>{const b=document.createElement('button');b.textContent=row.label;b.title=`${row.label} · ${fmtHash(row.profiles.master.sha256)}`;b.addEventListener('click',async()=>{state.currentRender=row;updateCurrentButtons();await showProfile('current-master');});return b;}));}
async function renderBatch(mode){if(!state.client)return;serviceState(`Rendering ${mode} batch…`);const result=await state.client.batch({...currentJob(),mode,count:numeric('sl-variant-count')});renderBatchStrip(result);serviceState(`${result.rows.length} canonical ${mode} renders ready for one-tap solo.`,'good');}
async function promoteCurrent(){if(!state.client)return;if(!window.confirm(`Promote the current canonical sound for ${state.binding.id}?\n\nThis updates the binding${currentTrace()?' and captured telemetry':''}, rebuilds master/runtime outputs, and refreshes stale state.`))return;serviceState('Promoting current sound and rebuilding canonical outputs…');const id=state.binding.id;const result=await state.client.promote(currentJob());serviceState(`Promoted ${result.outputs.length} outputs; refreshing manifest…`,'good');await reloadManifest(id);const caps=await state.client.connect();state.capabilities=caps;$('sl-canonical-state').textContent=caps.build.ok?'current':'stale';$('sl-build-state').textContent=caps.build.ok?`${caps.build.outputs} promoted outputs`:'promoted outputs stale';}
async function importSource(){if(!state.client)return;const file=$('sl-source-file').files?.[0];if(!file)throw new Error('Choose a WAV file first');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));serviceState(`Importing frozen source ${file.name}…`);const result=await state.client.importSource({fileName:file.name,id:$('sl-source-id').value||file.name.replace(/\.wav$/i,''),role:$('sl-source-role').value,provenance:{provider:$('sl-source-provider').value||'recorded'},bytesBase64:btoa(binary)});const sources=await state.client.sources();state.manifest.previewModel.sources=sources.sources;$('sl-source').replaceChildren(...sourceNodes(result.source.id));$('sl-source').value=result.source.id;updateSourceMeta();renderPreview();renderReferenceExplorer();serviceState(`Imported ${result.source.id} · sha ${fmtHash(result.source.sha256)}.`,'good');}

async function reloadManifest(bindingId){const response=await fetch(state.manifestUrl,{cache:'no-store'});if(!response.ok)throw new Error(`SoundLab manifest reload failed (${response.status})`);state.manifest=assertSoundLabManifest(await response.json());$('sl-project').textContent=`${state.manifest.project} · ${state.manifest.rendererVersion}`;$('sl-renderer').textContent=state.manifest.rendererVersion;populateCases();setBinding(bindingId||state.manifest.bindings[0]?.id);}
function installEvents(){
  installReferenceMap();
  for(const id of primaryRangeControls){const input=$(`sl-${id}`);input.addEventListener('input',()=>{const out=$(`sl-${id}-out`);if(out)out.textContent=Number(input.value).toFixed(2);updateChangedState();});input.addEventListener('change',renderPreview);installPointerRange(id);}installSceneWindow();
  for(const id of ['sl-material','sl-object-profile','sl-style-profile','sl-source'])$(id).addEventListener('change',renderPreview);
  for(const id of rangeControls){const input=$(`sl-${id}`);input.addEventListener('input',()=>{const out=$(`sl-${id}-out`);if(out)out.textContent=Number(input.value).toFixed(2);updateChangedState();});input.addEventListener('change',renderPreview);}
  $('sl-variant-count').addEventListener('change',()=>{updateChangedState();renderPreview();});$('sl-seed').addEventListener('change',renderPreview);$('sl-variant').addEventListener('change',()=>showProfile(state.displayProfile));$('sl-case-picker').addEventListener('change',()=>setBinding($('sl-case-picker').value));
  $('sl-apply-description').addEventListener('click',applySoundDescription);$('sl-description').addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();applySoundDescription();}});
  document.querySelectorAll('.reset-control').forEach(button=>button.addEventListener('click',()=>resetControl(button.dataset.reset)));document.querySelectorAll('[data-snapshot-save]').forEach(button=>button.addEventListener('click',()=>saveSnapshot(button.dataset.snapshotSave)));document.querySelectorAll('[data-snapshot-load]').forEach(button=>button.addEventListener('click',()=>applySnapshot(state.snapshots[button.dataset.snapshotLoad])));
  $('sl-render-preview').addEventListener('click',renderPreview);$('sl-play-preview').addEventListener('click',()=>playProfile('preview'));$('sl-play-master').addEventListener('click',()=>playProfile('master'));$('sl-play-runtime').addEventListener('click',()=>playProfile('runtime'));document.querySelectorAll('[data-profile]').forEach(button=>button.addEventListener('click',()=>showProfile(button.dataset.profile)));
  $('sl-start-native').addEventListener('click',()=>startNative().catch(handleNativeError));$('sl-native-input-file').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{await loadNativeInput(file);}catch(error){handleNativeError(error);}finally{event.target.value='';}});$('sl-reset-native').addEventListener('click',()=>{stopSceneDraft();state.runtime?.reset();});$('sl-toggle-native').addEventListener('click',()=>setNativeCollapsed($('sl-native-panel').dataset.collapsed!=='true'));$('sl-play-isolated').addEventListener('click',()=>playProfile(state.currentRender?'current-master':'preview'));$('sl-replay-draft').addEventListener('click',()=>replaySelectedEvent('draft'));$('sl-replay-context').addEventListener('click',()=>replaySelectedEvent('native'));$('sl-scene-contact').addEventListener('click',selectSceneContact);
  $('sl-clear-capture').addEventListener('click',()=>{state.events=[];state.selectedEvent=-1;state.useCapturedTelemetry=false;$('sl-use-capture').setAttribute('aria-pressed','false');$('sl-telemetry').textContent='Capture cleared.';renderTimeline();});$('sl-use-capture').addEventListener('click',()=>{state.useCapturedTelemetry=!state.useCapturedTelemetry;$('sl-use-capture').setAttribute('aria-pressed',String(state.useCapturedTelemetry));});$('sl-export-capture').addEventListener('click',()=>downloadJson(`${state.manifest.project}-${state.binding.id}-trace.json`,currentTrace()||telemetryTrace(state.manifest.project,state.events,{binding:state.binding.id})));
  $('sl-render-canonical').addEventListener('click',()=>renderCanonical().catch(error=>serviceState(error.message,'bad')));$('sl-render-variants').addEventListener('click',()=>renderBatch('variants').catch(error=>serviceState(error.message,'bad')));$('sl-render-materials').addEventListener('click',()=>renderBatch('materials').catch(error=>serviceState(error.message,'bad')));$('sl-render-sweep').addEventListener('click',()=>renderBatch('strength').catch(error=>serviceState(error.message,'bad')));$('sl-promote').addEventListener('click',()=>promoteCurrent().catch(error=>serviceState(error.message,'bad')));$('sl-import-source').addEventListener('click',()=>importSource().catch(error=>serviceState(error.message,'bad')));$('sl-source-file').addEventListener('change',()=>{$('sl-import-source').disabled=!state.client||!$('sl-source-file').files?.length;});
}

async function init(){const params=new URLSearchParams(location.search),manifestPath=params.get('manifest')||'rdx/data/soundlab/manifest.json',serviceBase=params.get('service');state.manifestUrl=new URL(manifestPath,document.baseURI);const response=await fetch(state.manifestUrl,{cache:'no-store'});if(!response.ok)throw new Error(`SoundLab manifest load failed (${response.status})`);state.manifest=assertSoundLabManifest(await response.json());$('sl-project').textContent=`${state.manifest.project} · ${state.manifest.rendererVersion}`;$('sl-renderer').textContent=state.manifest.rendererVersion;$('sl-build-state').textContent=`${state.manifest.outputs.length} promoted outputs`;populateCases();setBinding(state.manifest.bindings[0]?.id);configureNativeInput();installPersistedDetails();installEvents();await connectAuthoringService(serviceBase);document.documentElement.dataset.soundlabReady='true';}
if(typeof document!=='undefined'&&document.getElementById('soundlab-app'))init().catch(error=>{$('sl-project').textContent=error.message;document.documentElement.dataset.soundlabError=error.message;console.error(error);});
