import { assertSoundLabManifest, bindingFor, deepMerge, materialOptions, outputsFor, resourceOptions, resolvePreviewResources, sourceOptions, telemetryTrace } from './rdx/src/soundlab/model.js';
import { renderImpactPreview, audioBufferFrom } from './rdx/src/soundlab/preview-renderer.js';
import { SoundLabAuthoringClient } from './rdx/src/soundlab/authoring-client.js';
import { loadRememberedRdxRom, rememberRdxRom, connectRdxRomDirectory, canConnectRdxRomDirectory, CORRECT_ROM_MESSAGE } from './rdx/src/runtime/rom-store.js';

const $=id=>document.getElementById(id);
const numeric=id=>Number($(id).value);
const state={manifest:null,manifestUrl:null,binding:null,preview:null,audio:null,decoded:new Map(),displayProfile:'preview',events:[],selectedEvent:-1,runtime:null,client:null,capabilities:null,currentRender:null,batch:null,useCapturedTelemetry:false,controlDefaults:{},snapshots:{A:null,B:null},romBytes:null,romSource:null,draftRevision:0,renderTimer:0,auditionMode:'current-draft',serviceBase:null,buildMeta:null,sceneState:null,sceneAnalysis:null};
const rangeControls=['size','roughness','hardness','transient','body','residual','damping','style-amount','covariance'];
const controlIds=['material','strength','object','size','roughness','hardness','transient','body','residual','damping','style','style-amount','variants','covariance','source'];
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
const close=(a,b,epsilon=.0001)=>Math.abs(Number(a)-Number(b))<=epsilon;

const readinessIds=['manifest','rom','native','audio','service','canonical','scene'];
function setReadiness(id,kind,label,detail=''){const node=$(`sl-ready-${id}`);if(!node)return;node.className=`sl-ready ${kind||'waiting'}`;node.querySelector('strong').textContent=label;node.querySelector('small').textContent=detail||node.querySelector('small').textContent;}
function updateAudioReadiness(){const value=state.audio?.state||'suspended';setReadiness('audio',value==='running'?'ready':'waiting',value==='running'?'ready':'locked',value==='running'?`${state.audio.sampleRate} Hz unlocked`:'tap Start scene or audition to unlock');}
function draftKey(){return state.manifest&&state.binding?`soundlab:draft:v1:${state.manifest.project}:${state.binding.id}`:'';}
function draftDocument(){return{schema:'soundlab.local-draft.v1',project:state.manifest.project,binding:state.binding.id,rendererVersion:state.manifest.rendererVersion,seed:Number($('sl-seed').value)>>>0,variant:selectedVariant(),auditionMode:state.auditionMode,controls:snapshotValues(),snapshots:clone(state.snapshots),expertOpen:!!$('sl-expert')?.open,updatedAt:new Date().toISOString()};}
function persistDraft(){if(!state.binding)return;try{localStorage.setItem(draftKey(),JSON.stringify(draftDocument()));}catch{}}
function applyDraftDocument(doc,{render=true}={}){if(!doc||doc.schema!=='soundlab.local-draft.v1'||doc.project!==state.manifest.project||doc.binding!==state.binding.id)throw new Error('Draft does not match the selected SoundLab project/binding');if(doc.controls)applySnapshot(doc.controls,{render:false});if(doc.seed!=null)$('sl-seed').value=String(Number(doc.seed)>>>0);if(doc.variant!=null)$('sl-variant').value=String(doc.variant);state.snapshots={A:null,B:null,...clone(doc.snapshots||{})};state.auditionMode=doc.auditionMode==='native'?'native':'current-draft';if($('sl-expert'))$('sl-expert').open=!!doc.expertOpen;updateAuditionButtons();if(render)renderPreview();}
function restoreDraft(){try{const raw=localStorage.getItem(draftKey());if(raw)applyDraftDocument(JSON.parse(raw),{render:false});}catch(error){console.warn('[soundlab] ignored invalid local draft',error);}}
function updateAuditionButtons(){const current=state.auditionMode==='current-draft';$('sl-scene-current')?.classList.toggle('active',current);$('sl-scene-current')?.setAttribute('aria-pressed',String(current));$('sl-scene-native')?.classList.toggle('active',!current);$('sl-scene-native')?.setAttribute('aria-pressed',String(!current));state.runtime?.setAuditionMode?.(state.auditionMode);}
function updateRomState(label,detail,kind='waiting'){if($('sl-rom-state'))$('sl-rom-state').textContent=label;if($('sl-rom-detail'))$('sl-rom-detail').textContent=detail;setReadiness('rom',kind,label,detail);$('sl-start-native').disabled=!state.romBytes||!state.binding?.scene;}
function setSceneState(value={}){state.sceneState=value;const phase=value.error?'error':value.phase||'waiting',running=phase==='running'||phase==='post-event'||phase==='restart';$('sl-scene-name').textContent=state.binding?.scene?.id||'No reviewed scene';$('sl-scene-status').textContent=value.error||`${phase}${Number.isFinite(value.frame)?` · frame ${value.frame}`:''}`;setReadiness('scene',value.error?'error':running?'ready':'waiting',value.error?'fixture error':running?'running':phase,value.error||state.binding?.scene?.id||'binding has no native scene');$('sl-scene-pause').disabled=!state.runtime;$('sl-reset-native').disabled=!state.runtime;$('sl-scene-pause').textContent=value.paused?'Play':'Pause';renderTimeline();}
function setLiveState(value={}){const armed=!!value.armed,rendering=Number(value.pendingRevision||0)>Number(value.revision||0);$('sl-live-route').textContent=value.error?'Native cue kept':armed?'Live draft armed':rendering?'Rendering…':state.auditionMode==='native'?'Promoted/native':'Native fallback';$('sl-draft-revision').textContent=`draft r${Number(value.revision||state.draftRevision||0)}`;}
function setSceneAnalysis(value={}){state.sceneAnalysis=value;if($('sl-brief-object'))$('sl-brief-object').textContent=value.object?`${value.object} → ${value.surface||'surface'}`:(state.binding?.match?.actorFamily||state.binding?.object||'Scene object');if($('sl-scene-read'))$('sl-scene-read').textContent=value.summary||'Reading scene motion…';}
function schedulePreviewRender(){clearTimeout(state.renderTimer);state.renderTimer=setTimeout(()=>renderPreview(),35);}
async function restoreRememberedRom(){try{const row=await loadRememberedRdxRom();if(row?.bytes){state.romBytes=row.bytes;state.romSource=row.source||'remembered';updateRomState(row.source==='linked-directory'?'RDX ROM linked':'RDX ROM remembered',`${row.bytes.length.toLocaleString()} verified bytes`,'ready');return;}}catch(error){updateRomState('Invalid remembered ROM',CORRECT_ROM_MESSAGE,'error');return;}updateRomState('RDX ROM required','Load Rick_Dangerous_DX_1.3.bin once; it is shared with Workbench and Level Editor.','waiting');}
async function loadRomFile(file){if(!file)return;try{const bytes=new Uint8Array(await file.arrayBuffer());await rememberRdxRom(bytes,{name:file.name});state.romBytes=bytes;state.romSource='file';updateRomState('RDX ROM remembered',`${state.romBytes.length.toLocaleString()} verified bytes`,'ready');}catch(error){state.romBytes=null;updateRomState('Invalid RDX ROM',CORRECT_ROM_MESSAGE,'error');throw error;}}
async function connectRomFolder(){try{const row=await connectRdxRomDirectory();state.romBytes=row.bytes;state.romSource='directory';updateRomState('RDX ROM linked',`${state.romBytes.length.toLocaleString()} verified bytes`,'ready');}catch(error){if(error?.name!=='AbortError')updateRomState('ROM folder unavailable',error.message||CORRECT_ROM_MESSAGE,'error');}}

function audioContext(){if(!state.audio){state.audio=new (window.AudioContext||window.webkitAudioContext)();state.audio.addEventListener?.('statechange',()=>{updateAudioReadiness();state.runtime?.audioStateChanged?.();});} $('sl-browser-rate').textContent=`${state.audio.sampleRate} Hz AudioContext`;updateAudioReadiness();return state.audio;}
function fmtHash(value=''){return value?value.slice(0,10):'—';}
function fmtRate(value){const rate=Number(value||0);return rate>=1000?`${(rate/1000).toLocaleString(undefined,{maximumFractionDigits:2})} kHz`:`${rate} Hz`;}
function fmtEncoding(value=''){const encoding=String(value||'').toLowerCase();if(encoding==='u8')return 'PCM8 unsigned';if(encoding==='pcm16')return 'PCM16';return encoding?encoding.toUpperCase():'source';}
function samplesOf(buffer){return buffer?.getChannelData?buffer.getChannelData(0):buffer?.samples||new Float32Array();}
function metrics(samples,sampleRate){let peak=0,last=-1;for(let i=0;i<samples.length;i++){const a=Math.abs(samples[i]);peak=Math.max(peak,a);if(a>.008)last=i;}return{peak,duration:last>=0?(last+1)*1000/sampleRate:0};}
function drawWaveform(samples){const canvas=$('sl-waveform'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#29313b';ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();if(!samples?.length)return;ctx.strokeStyle='#e4ad55';ctx.lineWidth=1;ctx.beginPath();const bucket=Math.max(1,Math.floor(samples.length/w));for(let x=0;x<w;x++){let lo=1,hi=-1;const start=x*bucket,end=Math.min(samples.length,start+bucket);for(let i=start;i<end;i++){lo=Math.min(lo,samples[i]);hi=Math.max(hi,samples[i]);}ctx.moveTo(x,(1-hi)*h/2);ctx.lineTo(x,(1-lo)*h/2);}ctx.stroke();}
function profileCaption(profile){return({preview:'Current browser preview','current-master':'Current canonical master','current-runtime':'Current runtime derivative',master:'Frozen promoted master',runtime:'Frozen shipping derivative'})[profile]||profile;}
function showAudio(render,{hash='',profile='preview',sourceSampleRate=null,encoding=''}={}){const samples=samplesOf(render),playbackRate=Number(render.sampleRate||48000),sourceRate=Number(sourceSampleRate||playbackRate);drawWaveform(samples);const m=metrics(samples,playbackRate);$('sl-metric-duration').textContent=`${m.duration.toFixed(1)} ms`;$('sl-metric-peak').textContent=`peak ${m.peak.toFixed(3)}`;$('sl-metric-rate').textContent=profile==='preview'?`${fmtRate(sourceRate)} preview`:`${fmtRate(sourceRate)} · ${fmtEncoding(encoding)} source`;$('sl-metric-hash').textContent=profile==='preview'?'non-authoritative':`sha ${fmtHash(hash)}`;$('sl-waveform-caption').textContent=profileCaption(profile);state.displayProfile=profile;document.querySelectorAll('[data-profile]').forEach(b=>b.classList.toggle('active',b.dataset.profile===profile));}
function playBuffer(buffer){const ctx=audioContext(),source=ctx.createBufferSource();source.buffer=buffer;source.connect(ctx.destination);source.start();}
function selectedMaterial(){return $('sl-material').value||state.binding.surface;}
function selectedVariant(){return Number($('sl-variant').value||0);}
function selectedObject(){return $('sl-object-profile').value||state.binding.object;}
function selectedStyle(){return $('sl-style-profile').value||state.binding.style;}
function rawResource(kind,id){return state.manifest.previewModel?.resources?.[kind]?.[id];}
function profileResources(){const binding={...state.binding,object:selectedObject(),style:selectedStyle(),surface:selectedMaterial()};return resolvePreviewResources(state.manifest,binding,selectedMaterial(),{object:selectedObject(),style:selectedStyle()});}

function authoringOverrides(){
  const base=profileResources(), overrides=clone(state.binding.overrides||{}), defaults=state.controlDefaults;
  const ensure=(kind,key,value)=>{overrides[kind]??={};let cursor=overrides[kind],parts=key.split('.');for(const part of parts.slice(0,-1))cursor=cursor[part]??={};cursor[parts.at(-1)]=value;};
  const size=numeric('sl-size'),damping=numeric('sl-damping'),covariance=numeric('sl-covariance');
  if(!close(size,defaults.size)||!close(damping,defaults.damping)){
    const modal=base.object.modal||{},root=Math.sqrt(size/Number(defaults.size||1)),damp=damping/Number(defaults.damping||1);
    ensure('object','modal.frequencyScale',Number(modal.frequencyScale??1)/root);
    ensure('object','modal.decayScale',Number(modal.decayScale??1)*root*damp);
    ensure('object','modal.coupling',Number(modal.coupling??1)*(0.85+0.15*size));
  }
  if(!close(covariance,defaults.covariance)){
    const factor=covariance/Number(defaults.covariance||1),v=base.object.variation||{};
    ensure('object','variation.frequency',Number(v.frequency??.018)*factor);ensure('object','variation.decay',Number(v.decay??.08)*factor);ensure('object','variation.brightness',Number(v.brightness??.035)*factor);
  }
  for(const [id,path] of [['roughness','contact.roughness'],['hardness','transient.hardness']])if(!close(numeric(`sl-${id}`),defaults[id]))ensure('material',path,numeric(`sl-${id}`));
  for(const id of ['transient','body','residual'])if(!close(numeric(`sl-${id}`),defaults[id]))ensure('recipe',`mix.${id}`,numeric(`sl-${id}`));
  const amount=numeric('sl-style-amount');if(!close(amount,defaults['style-amount'])){
    const f=base.style.finishing||{},ratio=amount/Number(defaults['style-amount']||1);
    ensure('style','finishing.drive',1+(Number(f.drive??1)-1)*ratio);ensure('style','finishing.softClip',Number(f.softClip??.75)*ratio);ensure('style','finishing.periodColoration',Number(f.periodColoration??0)*ratio);
  }
  const source=$('sl-source').value,defaultSource=String(defaults.source||'');if(source!==defaultSource)ensure('material','residual.source',source||null);
  return overrides;
}
function currentBinding(){return{...state.binding,surface:selectedMaterial(),object:selectedObject(),style:selectedStyle(),strength:numeric('sl-strength'),variants:Math.max(1,Math.min(16,Math.round(numeric('sl-variant-count')||1))),overrides:authoringOverrides()};}
function currentResources(){const binding=currentBinding();return resolvePreviewResources(state.manifest,binding,binding.surface,{object:binding.object,style:binding.style});}
function currentTrace(){return state.useCapturedTelemetry&&state.events.length?telemetryTrace(state.manifest.project,state.events,{binding:state.binding.id}):null;}
function currentJob(){const binding=currentBinding();return{bindingId:binding.id,surface:binding.surface,object:binding.object,recipe:binding.recipe,style:binding.style,strength:binding.strength,variants:binding.variants,seed:Number($('sl-seed').value)>>>0,overrides:binding.overrides,...(currentTrace()?{telemetryTrace:currentTrace(),useCapturedTelemetry:true}:{})};}

function renderPreview(){const revision=++state.draftRevision;state.runtime?.beginDraftRevision?.(revision);try{const binding=currentBinding(),{material,object,recipe,style}=currentResources(),render=renderImpactPreview({sampleRate:Number(state.manifest.previewModel?.renderer?.sampleRate||48000),strength:binding.strength,seed:Number($('sl-seed').value)>>>0,material,object,recipe,style});state.preview=render;showAudio(render,{profile:'preview',sourceSampleRate:render.sampleRate});updateChangedState();persistDraft();$('sl-draft-revision')&&($('sl-draft-revision').textContent=`draft r${revision}`);if(state.runtime&&state.audio){const buffer=audioBufferFrom(state.audio,render);state.runtime.setDraftBuffer?.(buffer,revision);state.runtime.setAuditionMode?.(state.auditionMode);}return render;}catch(error){state.runtime?.failDraftRevision?.(revision,error);throw error;}}
function outputRow(profile){return outputsFor(state.manifest,state.binding.id,profile).find(row=>row.variant===selectedVariant())||outputsFor(state.manifest,state.binding.id,profile)[0];}
async function decodeUrl(key,url){if(state.decoded.has(key))return state.decoded.get(key);const response=await fetch(new URL(url,document.baseURI),{cache:'no-store'});if(!response.ok)throw new Error(`audio load failed (${response.status})`);const buffer=await audioContext().decodeAudioData(await response.arrayBuffer());state.decoded.set(key,buffer);return buffer;}
async function decodedOutput(profile){const row=outputRow(profile);if(!row)throw new Error(`No ${profile} output for ${state.binding.id}`);const buffer=await decodeUrl(`promoted:${profile}:${row.variant}:${row.sha256}`,new URL(row.file,state.manifestUrl));return{buffer,row};}
function currentProfile(profile){const key=profile==='current-master'?'master':'runtime',row=state.currentRender?.profiles?.[key];if(!row)throw new Error('Render the current canonical sound first');return{key,row};}
async function showProfile(profile){
  if(profile==='preview'){if(!state.preview)renderPreview();showAudio(state.preview,{profile,sourceSampleRate:state.preview.sampleRate});return;}
  if(profile.startsWith('current-')){const {key,row}=currentProfile(profile),buffer=await decodeUrl(`current:${key}:${row.sha256}`,row.url);showAudio(buffer,{hash:row.sha256,profile,sourceSampleRate:row.sampleRate,encoding:row.encoding});return;}
  const {buffer,row}=await decodedOutput(profile);showAudio(buffer,{hash:row.sha256,profile,sourceSampleRate:row.sampleRate,encoding:row.encoding});
}
async function playProfile(profile){if(profile==='preview'){playBuffer(audioBufferFrom(audioContext(),state.preview||renderPreview()));return;}if(profile.startsWith('current-')){const {key,row}=currentProfile(profile);playBuffer(await decodeUrl(`current:${key}:${row.sha256}`,row.url));return;}const {buffer}=await decodedOutput(profile);playBuffer(buffer);}

function syncCaseControls(){document.querySelectorAll('.case-button').forEach(b=>b.classList.toggle('active',b.dataset.id===state.binding.id));if($('sl-case-picker').value!==state.binding.id)$('sl-case-picker').value=state.binding.id;}
function optionNodes(rows,selected,label=row=>row.id.replaceAll('-',' ')){return rows.map(row=>new Option(label(row),row.id,row.id===selected,row.id===selected));}
function sourceNodes(selected){return [new Option('Procedural residual','',!selected,!selected),...sourceOptions(state.manifest).map(row=>new Option(`${row.id} · ${row.role}`,row.id,row.id===selected,row.id===selected))];}
function plainRangeLabel(id,value){const v=Number(value);if(id==='sl-strength')return v<.25?'gentle':v<.55?'solid':v<.82?'heavy':'forceful';if(id==='sl-size')return v<.8?'lighter':v<1.02?'balanced':v<1.22?'deep':'very deep';if(id==='sl-roughness')return v<.25?'smooth':v<.5?'grainy':v<.75?'rocky':'very rocky';if(id==='sl-hardness')return v<.25?'soft':v<.5?'rounded':v<.75?'hard':'sharp';if(id==='sl-damping')return v<.8?'short':v<1.05?'tight':v<1.3?'ringing':'long ring';return null;}
function updateSoundColor(){if($('sl-sound-color'))$('sl-sound-color').textContent=`Sound color: ${plainRangeLabel('sl-strength',numeric('sl-strength'))} · ${plainRangeLabel('sl-size',numeric('sl-size'))} · ${plainRangeLabel('sl-roughness',numeric('sl-roughness'))} · ${plainRangeLabel('sl-hardness',numeric('sl-hardness'))} · ${plainRangeLabel('sl-damping',numeric('sl-damping'))}`;if($('sl-brief-object')&&state.binding)$('sl-brief-object').textContent=`${String(state.binding.match?.actorFamily||state.binding.object).replaceAll('-',' ')} → ${String(selectedMaterial()).replaceAll('-',' ')}`;}
function setRange(id,value){$(id).value=String(value);const out=$(`${id}-out`);if(out)out.textContent=plainRangeLabel(id,value)||Number(value).toFixed(2);updateSoundColor();}
function setBinding(id){
  if(state.runtime){state.runtime.stop?.();state.runtime=null;setReadiness('native','waiting','not started','authoritative runtime');}state.binding=bindingFor(state.manifest,id);state.sceneState=null;state.sceneAnalysis=null;syncCaseControls();state.currentRender=null;state.batch=null;state.decoded.clear();state.events=[];state.selectedEvent=-1;state.useCapturedTelemetry=false;$('sl-use-capture').setAttribute('aria-pressed','false');
  $('sl-object').textContent=state.binding.object;$('sl-recipe').textContent=state.binding.recipe;$('sl-style').textContent=state.binding.style;$('sl-event').textContent=state.binding.event;
  $('sl-brief-object').textContent=`${String(state.binding.match?.actorFamily||state.binding.object).replaceAll('-',' ')} → ${String(state.binding.surface).replaceAll('-',' ')}`;$('sl-scene-read').textContent='Start the native scene to read its motion and contact.';
  $('sl-material').replaceChildren(...optionNodes(materialOptions(state.manifest),state.binding.surface));$('sl-object-profile').replaceChildren(...optionNodes(resourceOptions(state.manifest,'objects'),state.binding.object));$('sl-style-profile').replaceChildren(...optionNodes(resourceOptions(state.manifest,'styles'),state.binding.style));
  const base=profileResources(),master=outputsFor(state.manifest,state.binding.id,'master');$('sl-variant').replaceChildren(...master.map(row=>new Option(`variant ${row.variant+1} · seed ${row.seed}`,String(row.variant))));$('sl-seed').value=String(master[0]?.seed||1);$('sl-source').replaceChildren(...sourceNodes(base.material.residual?.source||''));
  state.controlDefaults={material:state.binding.surface,strength:Number(state.binding.strength??.7),object:state.binding.object,size:1,roughness:Number(base.material.contact?.roughness??.5),hardness:Number(base.material.transient?.hardness??.5),transient:Number(base.recipe.mix?.transient??.6),body:Number(base.recipe.mix?.body??.8),residual:Number(base.recipe.mix?.residual??.3),damping:1,style:state.binding.style,'style-amount':1,variants:Number(state.binding.variants||4),covariance:1,source:String(base.material.residual?.source||'')};
  $('sl-strength').value=String(state.controlDefaults.strength);$('sl-strength-out').textContent=plainRangeLabel('sl-strength',state.controlDefaults.strength);setRange('sl-size',1);setRange('sl-roughness',state.controlDefaults.roughness);setRange('sl-hardness',state.controlDefaults.hardness);setRange('sl-transient',state.controlDefaults.transient);setRange('sl-body',state.controlDefaults.body);setRange('sl-residual',state.controlDefaults.residual);setRange('sl-damping',1);setRange('sl-style-amount',1);setRange('sl-covariance',1);$('sl-variant-count').value=String(state.controlDefaults.variants);updateSourceMeta();loadSnapshots();restoreDraft();state.preview=null;renderPreview();renderTimeline();updateCurrentButtons();$('sl-batch-strip').replaceChildren();$('sl-scene-name').textContent=state.binding.scene?.id||'No reviewed scene';setSceneState({phase:state.binding.scene?'waiting':'unavailable'});$('sl-start-native').disabled=!state.romBytes||!state.binding.scene;updateAuditionButtons();
}
function populateCases(){const rows=state.manifest.bindings;$('sl-case-list').replaceChildren(...rows.map(binding=>{const b=document.createElement('button');b.className='case-button';b.dataset.id=binding.id;b.innerHTML=`<strong>${binding.event}</strong><small>${binding.match?.actorFamily||binding.id} · ${binding.surface}</small>`;b.addEventListener('click',()=>setBinding(binding.id));return b;}));$('sl-case-picker').replaceChildren(...rows.map(binding=>new Option(binding.event,binding.id)));$('sl-case-count').textContent=`${rows.length}`;}

function controlValue(id){if(id==='material')return selectedMaterial();if(id==='strength')return numeric('sl-strength');if(id==='object')return selectedObject();if(id==='style')return selectedStyle();if(id==='variants')return numeric('sl-variant-count');if(id==='source')return $('sl-source').value;return numeric(`sl-${id}`);}
function changed(id){const a=controlValue(id),b=state.controlDefaults[id];return typeof a==='number'&&!Number.isNaN(a)?!close(a,b):String(a)!==String(b??'');}
function updateChangedState(){let count=0;for(const id of controlIds){const row=document.querySelector(`[data-control="${id}"]`);if(!row)continue;const yes=changed(id);row.classList.toggle('changed',yes);if(yes)count+=1;}$('sl-changed-count').textContent=count?`${count} changed`:'profile defaults';$('sl-object').textContent=selectedObject();$('sl-style').textContent=selectedStyle();updateSourceMeta();updateSoundColor();}
function resetControl(id){const value=state.controlDefaults[id];if(id==='material')$('sl-material').value=value;else if(id==='strength'){$('sl-strength').value=value;$('sl-strength-out').textContent=plainRangeLabel('sl-strength',value);}else if(id==='object')$('sl-object-profile').value=value;else if(id==='style')$('sl-style-profile').value=value;else if(id==='variants')$('sl-variant-count').value=value;else if(id==='source')$('sl-source').value=value;else setRange(`sl-${id}`,value);renderPreview();}
function snapshotValues(){return Object.fromEntries(controlIds.map(id=>[id,controlValue(id)]));}
function applySnapshot(values,{render=true}={}){if(!values)return;for(const [id,value] of Object.entries(values)){if(id==='material')$('sl-material').value=value;else if(id==='strength'){$('sl-strength').value=value;$('sl-strength-out').textContent=plainRangeLabel('sl-strength',value);}else if(id==='object')$('sl-object-profile').value=value;else if(id==='style')$('sl-style-profile').value=value;else if(id==='variants')$('sl-variant-count').value=value;else if(id==='source')$('sl-source').value=value;else if(document.getElementById(`sl-${id}`))setRange(`sl-${id}`,value);}if(render)renderPreview();}
function snapshotKey(){return `soundlab:snapshots:${state.manifest.project}:${state.binding.id}`;}
function loadSnapshots(){try{state.snapshots={A:null,B:null,...JSON.parse(localStorage.getItem(snapshotKey())||'{}')};}catch{state.snapshots={A:null,B:null};}}
function saveSnapshot(slot){state.snapshots[slot]=snapshotValues();localStorage.setItem(snapshotKey(),JSON.stringify(state.snapshots));persistDraft();$('sl-promotion-state').textContent=`Stored parameter snapshot ${slot}.`;}

function updateSourceMeta(){const id=$('sl-source')?.value,row=sourceOptions(state.manifest).find(item=>item.id===id);$('sl-source-meta').textContent=row?`${row.id} · ${row.role} · onset ${row.onsetSample||0} · sha ${fmtHash(row.sha256)} · ${row.provenance?.provider||'unknown provider'}${row.provenance?.model?` / ${row.provenance.model}`:''}`:'No frozen source selected; procedural residual is used.';}
function renderTimeline(){
  const track=$('sl-event-timeline'),events=state.events,marker=$('sl-event-marker'),range=$('sl-window-range'),startHandle=$('sl-window-start'),endHandle=$('sl-window-end');
  track.querySelectorAll('b').forEach(node=>node.remove());
  const windowState=state.sceneState?.window||{start:0,end:Number(state.binding?.scene?.proof?.maxFrames||180)+Number(state.binding?.scene?.postEventFrames||0),total:Number(state.binding?.scene?.proof?.maxFrames||180)+Number(state.binding?.scene?.postEventFrames||0),editable:false};
  const total=Math.max(1,Number(windowState.total)||1),start=Math.max(0,Math.min(total,Number(windowState.start)||0)),finish=Math.max(start+1,Math.min(total,Number(windowState.end)||total));
  const startPct=100*start/total,endPct=100*finish/total;range.style.left=`${startPct}%`;range.style.width=`${Math.max(0,endPct-startPct)}%`;startHandle.style.left=`${startPct}%`;endHandle.style.left=`${endPct}%`;startHandle.disabled=!windowState.editable;endHandle.disabled=!windowState.editable;
  events.slice(-12).forEach((event,index0)=>{const absolute=events.length-Math.min(12,events.length)+index0,frame=Number(event.sceneFrame);if(!Number.isFinite(frame))return;const b=document.createElement('b');b.style.left=`${100*Math.max(0,Math.min(total,frame))/total}%`;b.classList.toggle('selected',absolute===state.selectedEvent);b.title=`${event.event} · scene frame ${frame}`;b.addEventListener('click',()=>{state.selectedEvent=absolute;renderTimeline();});track.append(b);});
  const event=events[state.selectedEvent]||events.at(-1);if(event&&Number.isFinite(Number(event.sceneFrame))){const pos=100*Math.max(0,Math.min(total,Number(event.sceneFrame)))/total;marker.style.left=`${pos}%`;marker.style.opacity='1';$('sl-event-readout').textContent=`${start}–${finish}f · ${event.event} at ${event.sceneFrame}f`;$('sl-telemetry').textContent=JSON.stringify(event,null,2);$('sl-replay-context').disabled=!state.runtime?.canReplayEvent?.(event.serial);}else{marker.style.opacity='.2';marker.style.left='0%';$('sl-event-readout').textContent=windowState.editable?`${start}–${finish}f`:'Play once to unlock trim handles';$('sl-replay-context').disabled=true;}
}
function showEvent(event){state.events.push(event);state.selectedEvent=state.events.length-1;renderTimeline();}
function installTimelineWindow(){
  const track=$('sl-event-timeline');let active=null,draft=null;
  const frameAt=event=>{const total=Math.max(1,Number(state.sceneState?.window?.total)||1),rect=track.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/Math.max(1,rect.width)));return Math.round(total*ratio);};
  const update=(kind,event)=>{const w=state.sceneState?.window;if(!w?.editable)return;const proof=Number(w.proofFrame),total=Number(w.total),frame=frameAt(event);draft={start:Number(w.start),end:Number(w.end),total,proofFrame:proof,editable:true};if(kind==='start')draft.start=Math.max(0,Math.min(proof-1,frame));else draft.end=Math.max(proof+1,Math.min(total,frame));state.sceneState={...state.sceneState,window:draft};renderTimeline();};
  for(const kind of ['start','end']){const handle=$(`sl-window-${kind}`);handle.addEventListener('pointerdown',event=>{if(handle.disabled)return;active={kind,id:event.pointerId};handle.setPointerCapture?.(event.pointerId);update(kind,event);event.preventDefault();});handle.addEventListener('pointermove',event=>{if(active?.id!==event.pointerId||active.kind!==kind)return;update(kind,event);event.preventDefault();});const finish=event=>{if(active?.id!==event.pointerId||active.kind!==kind)return;update(kind,event);if(handle.hasPointerCapture?.(event.pointerId))handle.releasePointerCapture(event.pointerId);active=null;const w=state.sceneState?.window;state.runtime?.setPreviewWindow?.(w.start,w.end);event.preventDefault();};handle.addEventListener('pointerup',finish);handle.addEventListener('pointercancel',()=>{active=null;});handle.addEventListener('keydown',event=>{if(handle.disabled||!['ArrowLeft','ArrowRight'].includes(event.key))return;const w=state.sceneState?.window,delta=event.key==='ArrowLeft'?-1:1;const start=kind==='start'?Number(w.start)+delta:Number(w.start),end=kind==='end'?Number(w.end)+delta:Number(w.end);state.runtime?.setPreviewWindow?.(start,end);event.preventDefault();});}
}
function downloadJson(name,value){const url=URL.createObjectURL(new Blob([`${JSON.stringify(value,null,2)}\n`],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
function setNativeCollapsed(collapsed){const panel=$('sl-native-panel');panel.dataset.collapsed=String(collapsed);$('sl-toggle-native').textContent=collapsed?'Show':'Hide';$('sl-toggle-native').setAttribute('aria-expanded',String(!collapsed));}
async function startNative(){const adapterPath=state.manifest.authoring?.nativeAdapter;if(!adapterPath)throw new Error(`Project ${state.manifest.project} does not provide a native preview adapter`);if(!state.romBytes)throw new Error(CORRECT_ROM_MESSAGE);if(!state.binding.scene)throw new Error(`Binding ${state.binding.id} has no reviewed native scene`);setNativeCollapsed(false);const ctx=audioContext();try{await ctx.resume?.();}catch{}updateAudioReadiness();setReadiness('native','waiting','starting','initializing xrick/WASM');try{const module=await import(new URL(adapterPath,state.manifestUrl));const SoundLabRuntime=module.SoundLabRuntime||module.default;if(typeof SoundLabRuntime!=='function')throw new Error(`Native adapter ${adapterPath} must export SoundLabRuntime or default`);state.runtime?.stop?.();state.runtime=new SoundLabRuntime({canvas:$('sl-native-canvas'),onEvent:showEvent,onStatus:text=>$('sl-native-status').textContent=text,onSceneState:setSceneState,onLiveState:setLiveState,onSceneAnalysis:setSceneAnalysis});await state.runtime.start({binding:state.binding,scene:state.binding.scene,romBytes:state.romBytes,audioContext:ctx});const buffer=audioBufferFrom(ctx,state.preview||renderPreview());state.runtime.beginDraftRevision?.(state.draftRevision);state.runtime.setDraftBuffer?.(buffer,state.draftRevision);state.runtime.setAuditionMode?.(state.auditionMode);setReadiness('native','ready','ready','ABI + bridge initialized');$('sl-start-native').disabled=true;$('sl-native-canvas').focus();}catch(error){state.runtime?.stop?.();state.runtime=null;setReadiness('native','error','unavailable',error.message);setSceneState({error:error.message});throw error;}}
async function replaySelectedEvent(){const event=state.events[state.selectedEvent];if(!event||!state.runtime?.replayEvent?.(event.serial))return;$('sl-native-status').textContent=`Replaying context before tick ${event.tick}`;$('sl-native-canvas').focus();}

function rangeValueAt(input,surface,clientX){const rect=surface.getBoundingClientRect(),min=Number(input.min||0),max=Number(input.max||1),step=Number(input.step||.01),ratio=Math.max(0,Math.min(1,(clientX-rect.left)/Math.max(1,rect.width))),raw=min+(max-min)*ratio,steps=Math.round((raw-min)/step);return Math.max(min,Math.min(max,min+steps*step));}
function installPointerRange(){const surface=$('sl-strength-surface'),input=$('sl-strength');let active=null;const update=event=>{input.value=String(rangeValueAt(input,surface,event.clientX));input.dispatchEvent(new Event('input',{bubbles:true}));};surface.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;active=event.pointerId;surface.setPointerCapture?.(active);input.focus({preventScroll:true});update(event);event.preventDefault();});surface.addEventListener('pointermove',event=>{if(event.pointerId!==active)return;update(event);event.preventDefault();});const finish=event=>{if(event.pointerId!==active)return;update(event);if(surface.hasPointerCapture?.(active))surface.releasePointerCapture(active);active=null;renderPreview();event.preventDefault();};surface.addEventListener('pointerup',finish);surface.addEventListener('pointercancel',event=>{if(event.pointerId!==active)return;if(surface.hasPointerCapture?.(active))surface.releasePointerCapture(active);active=null;});}
function installPersistedDetails(){document.querySelectorAll('details[data-persist-key]').forEach(details=>{const key=`soundlab:open:${details.dataset.persistKey}`;try{const stored=localStorage.getItem(key);if(stored!==null)details.open=stored==='1';}catch{}details.addEventListener('toggle',()=>{try{localStorage.setItem(key,details.open?'1':'0');}catch{}});});}

function updateCurrentButtons(){const enabled=!!state.currentRender;for(const profile of ['current-master','current-runtime'])document.querySelector(`[data-profile="${profile}"]`).disabled=!enabled;}
function serviceState(text,kind=''){$('sl-promotion-state').textContent=text;$('sl-promotion-state').className=`promotion-state ${kind}`.trim();}
function setServiceEnabled(enabled){for(const id of ['sl-render-canonical','sl-render-variants','sl-render-materials','sl-render-sweep','sl-promote','sl-import-source'])$(id).disabled=!enabled;$('sl-canonical-panel').hidden=!enabled;}
async function connectAuthoringService(){if(!state.serviceBase){state.client=null;state.capabilities=null;setServiceEnabled(false);setReadiness('service','waiting','not configured','standalone hosted authoring');setReadiness('canonical','waiting','not connected','connect development authoring service');return;}setReadiness('service','waiting','connecting',state.serviceBase);state.client=new SoundLabAuthoringClient(state.serviceBase);try{state.capabilities=await state.client.connect();if(!state.capabilities?.connected)throw new Error('SoundLab authoring service unavailable');setServiceEnabled(true);setReadiness('service','ready','ready','canonical authoring connected');setReadiness('canonical',state.capabilities.build.ok?'ready':'error',state.capabilities.build.ok?'current':'stale',state.capabilities.build.ok?`${state.capabilities.build.outputs} promoted outputs`:(state.capabilities.build.problems?.[0]||'build stale'));$('sl-authoring-mode').textContent='connected authoring';$('sl-authoring-mode').className='sl-pill';$('sl-author-mode-caption').textContent='preview + canonical';$('sl-service-detail').textContent='Canonical renderer and promotion are connected to this development host.';if(state.capabilities.capabilities?.nativePreview===false){const reason=state.capabilities.nativePreviewReason||'Native preview package is unavailable.';$('sl-native-status').textContent=reason;setReadiness('native','error','unavailable',reason);}$('sl-canonical-state').textContent=state.capabilities.build.ok?'current':'stale';$('sl-build-state').textContent=state.capabilities.build.ok?`${state.capabilities.build.outputs} promoted outputs`:'promoted outputs stale';$('sl-build-state').classList.toggle('stale',!state.capabilities.build.ok);serviceState(state.capabilities.build.ok?'Canonical build is current.':state.capabilities.build.problems[0]||'Canonical build is stale.',state.capabilities.build.ok?'good':'bad');const sources=await state.client.sources();state.manifest.previewModel.sources=sources.sources;const selected=$('sl-source').value;$('sl-source').replaceChildren(...sourceNodes(selected));updateSourceMeta();}catch(error){state.client=null;state.capabilities=null;setServiceEnabled(false);setReadiness('service','error','unavailable',error.message||'connection failed');setReadiness('canonical','waiting','not connected','authoring service unavailable');}}
async function renderCanonical(){if(!state.client)return;serviceState('Rendering current canonical master + runtime…');const result=await state.client.render(currentJob());state.currentRender=result;state.decoded.clear();updateCurrentButtons();serviceState(`Current canonical ready · master ${fmtHash(result.profiles.master.sha256)} · runtime ${fmtHash(result.profiles.runtime.sha256)}`,'good');await showProfile('current-master');}
function renderBatchStrip(result){state.batch=result;$('sl-batch-strip').replaceChildren(...result.rows.map(row=>{const b=document.createElement('button');b.textContent=row.label;b.title=`${row.label} · ${fmtHash(row.profiles.master.sha256)}`;b.addEventListener('click',async()=>{state.currentRender=row;updateCurrentButtons();await showProfile('current-master');});return b;}));}
async function renderBatch(mode){if(!state.client)return;serviceState(`Rendering ${mode} batch…`);const result=await state.client.batch({...currentJob(),mode,count:numeric('sl-variant-count')});renderBatchStrip(result);serviceState(`${result.rows.length} canonical ${mode} renders ready for one-tap solo.`,'good');}
async function promoteCurrent(){if(!state.client)return;if(!window.confirm(`Promote the current canonical sound for ${state.binding.id}?\n\nThis updates the binding${currentTrace()?' and captured telemetry':''}, rebuilds master/runtime outputs, and refreshes stale state.`))return;serviceState('Promoting current sound and rebuilding canonical outputs…');const id=state.binding.id;const result=await state.client.promote(currentJob());serviceState(`Promoted ${result.outputs.length} outputs; refreshing manifest…`,'good');await reloadManifest(id);const caps=await state.client.connect();state.capabilities=caps;$('sl-canonical-state').textContent=caps.build.ok?'current':'stale';$('sl-build-state').textContent=caps.build.ok?`${caps.build.outputs} promoted outputs`:'promoted outputs stale';}
async function importSource(){if(!state.client)return;const file=$('sl-source-file').files?.[0];if(!file)throw new Error('Choose a WAV file first');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));serviceState(`Importing frozen source ${file.name}…`);const result=await state.client.importSource({fileName:file.name,id:$('sl-source-id').value||file.name.replace(/\.wav$/i,''),role:$('sl-source-role').value,provenance:{provider:$('sl-source-provider').value||'recorded'},bytesBase64:btoa(binary)});const sources=await state.client.sources();state.manifest.previewModel.sources=sources.sources;$('sl-source').replaceChildren(...sourceNodes(result.source.id));$('sl-source').value=result.source.id;updateSourceMeta();renderPreview();serviceState(`Imported ${result.source.id} · sha ${fmtHash(result.source.sha256)}.`,'good');}

async function reloadManifest(bindingId){const response=await fetch(state.manifestUrl,{cache:'no-store'});if(!response.ok)throw new Error(`SoundLab manifest reload failed (${response.status})`);state.manifest=assertSoundLabManifest(await response.json());$('sl-project').textContent=`${state.manifest.project} · ${state.manifest.rendererVersion}`;$('sl-renderer').textContent=state.manifest.rendererVersion;populateCases();setBinding(bindingId||state.manifest.bindings[0]?.id);}
function installEvents(){
  $('sl-strength').addEventListener('input',()=>{$('sl-strength-out').textContent=plainRangeLabel('sl-strength',numeric('sl-strength'));updateSoundColor();updateChangedState();schedulePreviewRender();});$('sl-strength').addEventListener('change',renderPreview);installPointerRange();installTimelineWindow();
  for(const id of ['sl-material','sl-object-profile','sl-style-profile','sl-source'])$(id).addEventListener('change',renderPreview);
  for(const id of rangeControls){const input=$(`sl-${id}`);input.addEventListener('input',()=>{const out=$(`sl-${id}-out`);if(out)out.textContent=plainRangeLabel(input.id,input.value)||Number(input.value).toFixed(2);updateChangedState();schedulePreviewRender();});input.addEventListener('change',renderPreview);}
  $('sl-variant-count').addEventListener('change',()=>{updateChangedState();renderPreview();});$('sl-seed').addEventListener('change',renderPreview);$('sl-variant').addEventListener('change',()=>{persistDraft();showProfile(state.displayProfile);});$('sl-case-picker').addEventListener('change',()=>setBinding($('sl-case-picker').value));
  document.querySelectorAll('.reset-control').forEach(button=>button.addEventListener('click',()=>resetControl(button.dataset.reset)));document.querySelectorAll('[data-snapshot-save]').forEach(button=>button.addEventListener('click',()=>saveSnapshot(button.dataset.snapshotSave)));document.querySelectorAll('[data-snapshot-load]').forEach(button=>button.addEventListener('click',()=>applySnapshot(state.snapshots[button.dataset.snapshotLoad])));
  $('sl-render-preview').addEventListener('click',renderPreview);$('sl-play-preview').addEventListener('click',()=>playProfile('preview'));$('sl-play-master').addEventListener('click',()=>playProfile('master'));$('sl-play-runtime').addEventListener('click',()=>playProfile('runtime'));document.querySelectorAll('[data-profile]').forEach(button=>button.addEventListener('click',()=>showProfile(button.dataset.profile)));
  $('sl-start-native').addEventListener('click',()=>startNative().catch(error=>$('sl-native-status').textContent=error.message));$('sl-reset-native').addEventListener('click',()=>state.runtime?.restartScene?.());$('sl-toggle-native').addEventListener('click',()=>setNativeCollapsed($('sl-native-panel').dataset.collapsed!=='true'));$('sl-play-isolated').addEventListener('click',()=>playProfile(state.currentRender?'current-master':'preview'));$('sl-replay-context').addEventListener('click',replaySelectedEvent);
  $('sl-rom-file').addEventListener('change',()=>loadRomFile($('sl-rom-file').files?.[0]).catch(error=>$('sl-native-status').textContent=error.message));$('sl-rom-folder').addEventListener('click',()=>connectRomFolder().catch(error=>$('sl-native-status').textContent=error.message));
  $('sl-scene-pause').addEventListener('click',()=>{const paused=$('sl-scene-pause').textContent==='Pause';state.runtime?.setPaused?.(paused);});$('sl-scene-loop').addEventListener('change',()=>state.runtime?.setLoop?.($('sl-scene-loop').checked));
  $('sl-scene-current').addEventListener('click',()=>{state.auditionMode='current-draft';updateAuditionButtons();persistDraft();});$('sl-scene-native').addEventListener('click',()=>{state.auditionMode='native';updateAuditionButtons();persistDraft();});
  $('sl-export-draft').addEventListener('click',()=>downloadJson(`${state.manifest.project}-${state.binding.id}-draft.json`,draftDocument()));$('sl-import-draft').addEventListener('change',async()=>{const file=$('sl-import-draft').files?.[0];if(!file)return;try{applyDraftDocument(JSON.parse(await file.text()));persistDraft();}catch(error){serviceState(error.message,'bad');}finally{$('sl-import-draft').value='';}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)state.runtime?.setPaused?.(true);});
  $('sl-clear-capture').addEventListener('click',()=>{state.events=[];state.selectedEvent=-1;state.useCapturedTelemetry=false;$('sl-use-capture').setAttribute('aria-pressed','false');$('sl-telemetry').textContent='Capture cleared.';renderTimeline();});$('sl-use-capture').addEventListener('click',()=>{state.useCapturedTelemetry=!state.useCapturedTelemetry;$('sl-use-capture').setAttribute('aria-pressed',String(state.useCapturedTelemetry));});$('sl-export-capture').addEventListener('click',()=>downloadJson(`${state.manifest.project}-${state.binding.id}-trace.json`,telemetryTrace(state.manifest.project,state.events,{binding:state.binding.id})));
  $('sl-render-canonical').addEventListener('click',()=>renderCanonical().catch(error=>serviceState(error.message,'bad')));$('sl-render-variants').addEventListener('click',()=>renderBatch('variants').catch(error=>serviceState(error.message,'bad')));$('sl-render-materials').addEventListener('click',()=>renderBatch('materials').catch(error=>serviceState(error.message,'bad')));$('sl-render-sweep').addEventListener('click',()=>renderBatch('strength').catch(error=>serviceState(error.message,'bad')));$('sl-promote').addEventListener('click',()=>promoteCurrent().catch(error=>serviceState(error.message,'bad')));$('sl-import-source').addEventListener('click',()=>importSource().catch(error=>serviceState(error.message,'bad')));$('sl-source-file').addEventListener('change',()=>{$('sl-import-source').disabled=!state.client||!$('sl-source-file').files?.length;});
}

async function init(){const params=new URLSearchParams(location.search),manifestPath=params.get('manifest')||'rdx/data/soundlab/manifest.json';const serviceSpec=params.get('service')||document.querySelector('meta[name="soundlab-service-base"]')?.content||'';state.serviceBase=serviceSpec?new URL(serviceSpec,document.baseURI).href:null;state.manifestUrl=new URL(manifestPath,document.baseURI);setReadiness('manifest','waiting','loading',state.manifestUrl.pathname);const response=await fetch(state.manifestUrl,{cache:'no-store'});if(!response.ok)throw new Error(`SoundLab manifest load failed (${response.status})`);state.manifest=assertSoundLabManifest(await response.json());setReadiness('manifest','ready','ready',`${state.manifest.project} · ${state.manifest.rendererVersion}`);$('sl-project').textContent=`${state.manifest.project} · ${state.manifest.rendererVersion}`;$('sl-renderer').textContent=state.manifest.rendererVersion;$('sl-build-state').textContent=`${state.manifest.outputs.length} promoted outputs`;try{const build=await fetch(new URL('web-build.json',document.baseURI),{cache:'no-store'});if(build.ok){state.buildMeta=await build.json();$('sl-project').textContent+=` · ${String(state.buildMeta.sourceCommit||state.buildMeta.source||'').slice(0,10)}`;}}catch{}await restoreRememberedRom();populateCases();setBinding(state.manifest.bindings[0]?.id);installPersistedDetails();installEvents();$('sl-rom-folder').hidden=!canConnectRdxRomDirectory();await connectAuthoringService();updateAudioReadiness();document.documentElement.dataset.soundlabReady='true';}
if(typeof document!=='undefined'&&document.getElementById('soundlab-app'))init().catch(error=>{$('sl-project').textContent=error.message;document.documentElement.dataset.soundlabError=error.message;console.error(error);});
