import { clear, element } from './dom.js';
import { createPnPicker } from './pn-picker.js';

function field(label,value,{type='number',step='1'}={}){const wrap=element('label',{className:'author-field'});wrap.append(element('span',{text:label}));const input=element('input',{attrs:{type,step,value:value ?? ''}});wrap.append(input);return{wrap,input};}
function pointFields(label,value=[0,0]){const row=element('div',{className:'author-row'});row.append(element('strong',{text:label}));const x=field('x',value?.[0]),y=field('y',value?.[1]);row.append(x.wrap,y.wrap);return{row,value:()=>[Number(x.input.value),Number(y.input.value)]};}
function rectFields(label,value=[0,0,0,0]){const row=element('div',{className:'author-row author-bounds'});row.append(element('strong',{text:label}));const fields=['x','y','w','h'].map((name,index)=>field(name,value?.[index]));for(const item of fields)row.append(item.wrap);return{row,value:()=>fields.map(item=>Number(item.input.value))};}
function actionButton(label,handler){const button=element('button',{text:label,attrs:{type:'button'}});button.addEventListener('click',handler);return button;}
function section(title){const row=element('section',{className:'author-section'});row.append(element('h3',{text:title}));return row;}
function currentPn(object){const value=object?.presentation?.pnByState?.snapshot ?? object?.presentation?.pnByState?.simulated ?? object?.states?.snapshot?.pn ?? object?.states?.simulated?.pn;return Number.isInteger(Number(value))?Number(value):'';}
function currentPatrol(object){return object?.controller?.reviewedPatrol || object?.sourceEvidence?.classic?.controller?.patrol || null;}
function reasonField(defaultValue='Reviewed in replacement Level Editor'){return field('Reason',defaultValue,{type:'text'});}
function contains(bounds,x,y){return Array.isArray(bounds)&&bounds.length>=4&&x>=Number(bounds[0])&&y>=Number(bounds[1])&&x<Number(bounds[0])+Number(bounds[2])&&y<Number(bounds[1])+Number(bounds[3]);}
function selectedAlignmentRegion(workspace,correspondence){
  const alignment=workspace?.effectiveRoom()?.layers?.alignment; if(!alignment)return null;
  if(correspondence?.regionId)return(alignment.regions||[]).find(row=>String(row.id)===String(correspondence.regionId))||null;
  const px=Number(correspondence?.side==='classic'?correspondence.classicX:correspondence.x)*8,py=Number(correspondence?.side==='classic'?correspondence.classicY:correspondence.y)*8;
  const key=correspondence?.side==='classic'?'classicBoundsPx':'rdxBoundsPx';return(alignment.regions||[]).find(row=>contains(row[key],px,py))||null;
}
function renderAlignmentAuthoring(container,{workspace,inspection}){
  const region=selectedAlignmentRegion(workspace,inspection.correspondence);if(!region){container.append(element('div',{className:'muted',text:'This cell is not owned by an editable reviewed alignment region.'}));return;}
  const box=section('Layer C · reviewed alignment');box.append(element('div',{className:'author-note',text:`${region.id} · ${region.status || 'unreviewed'} · ${region.authority || 'unknown authority'}`}));
  const dx=field('dx px',region.transform?.dxPx||0),dy=field('dy px',region.transform?.dyPx||0),reason=reasonField('Reviewed correspondence shift');box.append(dx.wrap,dy.wrap,reason.wrap);
  box.append(actionButton('Apply regional shift',()=>workspace.upsertCorrection({type:'alignment-exception',target:String(region.id),value:{transform:{type:'translate',dxPx:Number(dx.input.value),dyPx:Number(dy.input.value)}},reason:reason.input.value})));container.append(box);
}
function renderCollisionAuthoring(container,{workspace,inspection}){
  const cell=inspection.collision,box=section('Layer D · exact 8×8 collision');box.append(element('div',{className:'author-note',text:`G8 ${cell.gx},${cell.gy} · raw ${cell.rawKind} · effective ${cell.effectiveKind}`}));
  if(cell.override?.action==='exit'){box.append(element('div',{className:'author-note',text:`Native exit ${cell.override.direction} · xrick rowout 0x${Number(cell.override.contactRow).toString(16)} → SM${Number(cell.override.targetSubmap).toString(16).toUpperCase().padStart(2,'0')} rowin 0x${Number(cell.override.rowIn).toString(16)}. Exit topology is reviewed source data, not a generic collision toggle.`}));container.append(box);return;}
  const semantic=element('select',{attrs:{'aria-label':'Reviewed collision semantic'}});for(const value of ['open','one-way','climb-through','lethal'])semantic.append(element('option',{text:value,attrs:{value}}));semantic.value=['open','one-way','climb-through','lethal'].includes(cell.effectiveKind)?cell.effectiveKind:(cell.effectiveKind==='ladder'?'climb-through':'open');const reason=reasonField('Reviewed exact 8×8 collision exception');box.append(semantic,reason.wrap);
  box.append(actionButton('Apply G8 exception',()=>workspace.upsertCorrection({type:'terrain-cell',target:`terrain:${workspace.room.id}`,value:{action:semantic.value,g8Bounds:[Number(cell.gx),Number(cell.gy),1,1]},reason:reason.input.value})));container.append(box);
}
export function renderAuthoringPanel(container,{workspace,inspection}={}){
  clear(container);if(!workspace?.room){container.append(element('div',{className:'muted',text:'Open a room to author changes.'}));return;}
  if(inspection?.kind==='correspondence-cell'){renderAlignmentAuthoring(container,{workspace,inspection});return;}
  if(inspection?.kind==='collision-cell'){renderCollisionAuthoring(container,{workspace,inspection});return;}
  const object=inspection?.object;if(inspection?.kind!=='semantic-object'||!object){container.append(element('div',{className:'muted',text:'Select an effective semantic entity, correspondence cell, or collision cell to edit reviewed data.'}));return;}
  const target=String(object.semanticId),reason=reasonField();container.append(reason.wrap);
  const identity=section('Type & presentation');const classField=field('Class',object.class||'',{type:'text'}),controller=field('Controller',object.controller?.entity ?? ''),pnField=field('PN',currentPn(object));identity.append(classField.wrap,controller.wrap,pnField.wrap);
  identity.append(createPnPicker({assets:workspace.assets,mapId:workspace.room.mapId,currentPn:currentPn(object),onSelect:pn=>{pnField.input.value=String(pn);}}));
  identity.append(actionButton('Apply type',()=>workspace.upsertCorrection({type:'entity-type',target,value:{class:classField.input.value,controllerEntity:controller.input.value===''?null:Number(controller.input.value)},reason:reason.input.value})),actionButton('Apply PN',()=>workspace.upsertCorrection({type:'presentation',target,value:{pn:Number(pnField.input.value)},reason:reason.input.value})));container.append(identity);
  const placement=section('Placement');const position=pointFields('Position',object.effective?.position||object.alignedBaseline?.origin||[0,0]),anchor=pointFields('Visual anchor',object.effective?.visualAnchor||object.effective?.position||[0,0]);placement.append(position.row,actionButton('Apply position',()=>workspace.upsertCorrection({type:'entity-position',target,value:{position:position.value()},reason:reason.input.value})),anchor.row,actionButton('Apply visual anchor',()=>workspace.upsertCorrection({type:'visual-anchor',target,value:{anchor:anchor.value()},reason:reason.input.value})));container.append(placement);
  const bounds=section('Typed bounds');for(const [label,type,key] of [['Visual','visual-bounds','visualBounds'],['Gameplay','gameplay-bounds','gameplayBounds'],['Trigger','trigger-bounds','triggerBounds']]){const value=object.effective?.[key];if(!Array.isArray(value))continue;const row=rectFields(label,value);bounds.append(row.row,actionButton(`Apply ${label.toLowerCase()} bounds`,()=>workspace.upsertCorrection({type,target,value:{bounds:row.value()},reason:reason.input.value})));}container.append(bounds);
  const patrol=currentPatrol(object);if(patrol?.start&&patrol?.end){const patrolSection=section('Native bounded patrol descriptor'),start=pointFields('Start',patrol.start),end=pointFields('End',patrol.end),latency=field('Startup ticks',patrol.startupLatencyTicks??patrol.startupLatency??0),direction=element('select');for(const value of ['right','left'])direction.append(element('option',{text:value,attrs:{value}}));direction.value=patrol.initialDirection||patrol.direction||'right';patrolSection.append(start.row,end.row,latency.wrap,direction,actionButton('Apply patrol descriptor',()=>workspace.upsertCorrection({type:'entity-patrol',target,value:{start:start.value(),end:end.value(),stepPx:2,initialDirection:direction.value,startupLatencyTicks:Number(latency.input.value)},reason:reason.input.value})));container.append(patrolSection);}
  const suppression=section('Disposition');const suppressed=element('input',{attrs:{type:'checkbox'}});suppressed.checked=String(object.implementationDisposition||'').startsWith('suppressed');const label=element('label',{className:'inline-check'});label.append(suppressed,document.createTextNode(' suppressed'));suppression.append(label,actionButton('Apply suppression',()=>workspace.upsertCorrection({type:'entity-suppression',target,value:{suppressed:suppressed.checked},reason:reason.input.value})));container.append(suppression);
}
