export const SOUND_SCORE_SCHEMA = 'soundlab.sound-score.v1';

const finite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const lerp=(a,b,t)=>a+(b-a)*t;
const frameRange=(value,fallback=[0,0])=>Array.isArray(value)&&value.length===2
  ? [Math.round(finite(value[0],fallback[0])),Math.round(finite(value[1],fallback[1]))]
  : [...fallback];
const title=value=>String(value||'segment').replaceAll(/[-_]+/g,' ').replace(/\b\w/g,char=>char.toUpperCase());

function samplesForSegment(sceneIntent,startFrame,endFrame){
  return (sceneIntent?.motion?.samples||[])
    .filter(row=>finite(row.frame)>=startFrame&&finite(row.frame)<=endFrame)
    .sort((a,b)=>finite(a.frame)-finite(b.frame));
}
function sampleSemantic(row,fallback='motion'){
  const dx=finite(row?.dx),dy=finite(row?.dy),ax=Math.abs(dx),ay=Math.abs(dy);
  if(ay>ax*1.2&&dy>.25)return 'falling';
  if(ax>ay*1.15&&ax>.25)return 'rolling';
  return fallback;
}
function motionSemantic(sceneIntent,startFrame,endFrame,fallback='motion'){
  const rows=samplesForSegment(sceneIntent,startFrame,endFrame);if(rows.length<2)return fallback;
  let horizontal=0,vertical=0,downward=0;for(const row of rows){horizontal+=Math.abs(finite(row.dx));vertical+=Math.abs(finite(row.dy));downward+=Math.max(0,finite(row.dy));}
  if(vertical>horizontal*1.2&&downward>=vertical*.55)return 'falling';
  if(horizontal>vertical*1.15)return 'rolling';
  return fallback;
}
function splitMotionPhases(segment,sceneIntent){
  const startFrame=Math.round(finite(segment.startFrame)),endFrame=Math.round(finite(segment.endFrame,startFrame)),sourceId=String(segment.id||'motion').toLowerCase();
  if(!['approach','settle'].includes(sourceId))return [{...segment,startFrame,endFrame}];
  const rows=samplesForSegment(sceneIntent,startFrame,endFrame);if(rows.length<3)return [{...segment,startFrame,endFrame}];
  const labels=rows.map(row=>sampleSemantic(row,null));for(let index=0;index<labels.length;index+=1)if(!labels[index])labels[index]=labels[index-1]||labels.slice(index+1).find(Boolean)||sourceId;
  const groups=[];for(let index=0;index<rows.length;index+=1){const label=labels[index];if(groups.at(-1)?.label===label)groups.at(-1).last=index;else groups.push({label,first:index,last:index});}
  for(let index=0;index<groups.length;index+=1){const group=groups[index],a=finite(rows[group.first].frame),b=finite(rows[group.last].frame);if(b-a>=1)continue;const neighbor=groups[index-1]||groups[index+1];if(neighbor)group.label=neighbor.label;}
  const merged=[];for(const group of groups){if(merged.at(-1)?.label===group.label)merged.at(-1).last=group.last;else merged.push({...group});}
  const meaningful=new Set(merged.map(row=>row.label).filter(label=>['rolling','falling','sliding'].includes(label)));if(meaningful.size<2)return [{...segment,startFrame,endFrame}];
  return merged.map((group,index)=>{const next=merged[index+1],groupStart=index===0?startFrame:Math.round(finite(rows[group.first].frame)),groupEnd=next?Math.max(groupStart,Math.round(finite(rows[next.first].frame))-1):endFrame;return{id:group.label,startFrame:groupStart,endFrame:groupEnd};});
}
export function semanticTypeForSegment(segment,sceneIntent){
  const id=String(segment?.id||'').toLowerCase(),action=String(sceneIntent?.action||'').toLowerCase(),startFrame=finite(segment?.startFrame),endFrame=finite(segment?.endFrame,startFrame);
  if(['contact','impact','hit'].includes(id))return 'impact';if(id==='rebound')return 'rebound';if(id==='settle')return motionSemantic(sceneIntent,startFrame,endFrame,'settle');
  if(['roll','rolling'].includes(id))return 'rolling';if(['fall','falling'].includes(id))return 'falling';if(['slide','sliding'].includes(id))return 'sliding';if(['scrape','mechanism','emitter'].includes(id))return id;
  if(id==='approach')return motionSemantic(sceneIntent,startFrame,endFrame,action==='roll'?'rolling':'approach');return id||action||'motion';
}
export function normalizeGesture(points,{samples=32}={}){
  const count=Math.max(2,Math.min(256,Math.round(finite(samples,32)))),input=(Array.isArray(points)?points:[]).map(point=>({x:finite(point?.x),y:finite(point?.y),pressure:clamp(finite(point?.pressure,1),0,1),width:clamp(finite(point?.width,point?.pressure??1),0,1),drawSpeed:Math.max(0,finite(point?.drawSpeed))}));
  if(!input.length)return[];if(input.length===1)return Array.from({length:count},(_,index)=>({progress:index/(count-1),...input[0]}));
  const distances=[0];for(let index=1;index<input.length;index+=1){const previous=input[index-1],point=input[index];distances.push(distances.at(-1)+Math.hypot(point.x-previous.x,point.y-previous.y));}
  const total=distances.at(-1);if(total<=1e-9)return Array.from({length:count},(_,index)=>({progress:index/(count-1),...input[0]}));
  const output=[];let cursor=1;for(let index=0;index<count;index+=1){const progress=index/(count-1),target=progress*total;while(cursor<distances.length-1&&distances[cursor]<target)cursor+=1;const before=Math.max(0,cursor-1),after=Math.min(input.length-1,cursor),span=Math.max(1e-9,distances[after]-distances[before]),amount=clamp((target-distances[before])/span,0,1),a=input[before],b=input[after];output.push({progress,x:lerp(a.x,b.x,amount),y:lerp(a.y,b.y,amount),pressure:lerp(a.pressure,b.pressure,amount),width:lerp(a.width,b.width,amount),drawSpeed:lerp(a.drawSpeed,b.drawSpeed,amount)});}
  return output.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,Number(value.toFixed(6))])));
}
function generatedGesturePoints(sceneIntent,segment,{samples=32}={}){
  const count=Math.max(8,Math.min(128,Math.round(finite(samples,32)))),rows=samplesForSegment(sceneIntent,segment.gameRange[0],segment.gameRange[1]),speedRows=rows.map(row=>Math.hypot(finite(row.dx),finite(row.dy))),maxSpeed=Math.max(1,...speedRows);
  const speedAt=progress=>{if(!speedRows.length)return 0;const position=clamp(progress,0,1)*(speedRows.length-1),a=Math.floor(position),b=Math.min(speedRows.length-1,Math.ceil(position)),t=position-a;return lerp(speedRows[a],speedRows[b],t);};
  const raw=Array.from({length:count},(_,index)=>{const progress=index/(count-1),energy=clamp(speedAt(progress)/maxSpeed,0,1),semantic=segment.semanticType;let y=.5;if(semantic==='rolling')y=.5+Math.sin(progress*Math.PI*6)*(.08+.1*energy);else if(semantic==='falling')y=.78-.48*energy;else if(semantic==='impact')y=.5-.34*Math.exp(-progress*7)*Math.cos(progress*Math.PI*4);else if(semantic==='rebound')y=.5-.25*Math.exp(-progress*3)*Math.cos(progress*Math.PI*5);else if(semantic==='mechanism')y=.5+Math.sin(progress*Math.PI*8)*.12;return{x:progress,y:clamp(y,0,1),pressure:clamp(.2+.8*energy,0,1),width:clamp(.25+.7*energy,0,1),drawSpeed:energy};});
  return normalizeGesture(raw,{samples:count});
}
const mapping=(id,source,target,inputRange,outputRange,curve='linear')=>({id,source,target,inputRange,outputRange,curve,clamp:true,enabled:true});
const withLayerDefaults=rows=>rows.map(row=>({envelope:{attackMs:0,releaseMs:0},variation:{amount:0,rateHz:4,seedOffset:0},...row}));
export function defaultLayersForSemanticType(semanticType){
  if(semanticType==='rolling')return withLayerDefaults([{id:'contact',label:'Contact',source:{type:'contact-train'},enabled:true,solo:false,gain:1,gestureId:'generated',mappings:[mapping('speed-density','native.speed','recipe.mapping.contactDensity',[0,8],[3.5,11],'ease-in')]},{id:'texture',label:'Stone texture',source:{type:'noise'},enabled:true,solo:false,gain:.45,gestureId:'generated',mappings:[mapping('wiggle-roughness','gesture.wiggle','material.contact.roughness',[0,1],[.3,.9],'smoothstep')]}]);
  if(semanticType==='falling')return withLayerDefaults([{id:'whoosh',label:'Air whoosh',source:{type:'noise',id:'fall-whoosh',params:{speedReference:8,brightness:.72}},enabled:true,solo:false,gain:.72,gestureId:'generated',mappings:[mapping('speed-brightness','native.speed','recipe.perceptual.brightness',[0,8],[.32,.82],'ease-in'),mapping('pressure-strength','gesture.pressure','binding.strength',[0,1],[.35,.82],'smoothstep')]},{id:'stone-movement',label:'Stone movement',source:{type:'resonant-body',id:'stone-movement',params:{modeLimit:2,decayScale:.45,frequencyScale:.72,speedReference:8}},enabled:true,solo:false,gain:.38,gestureId:'generated',mappings:[mapping('wiggle-roughness','gesture.wiggle','material.contact.roughness',[0,1],[.28,.86],'smoothstep')]}]);
  if(semanticType==='impact')return withLayerDefaults([{id:'transient',label:'Transient',source:{type:'procedural',id:'impact-transient',params:{decayMs:18}},enabled:true,solo:false,gain:1,gestureId:'generated',mappings:[mapping('pressure-transient','gesture.pressure','recipe.mapping.transientGain',[0,1],[.7,1.35],'smoothstep')]},{id:'body',label:'Stone body',source:{type:'resonant-body',id:'impact-body',params:{modeLimit:4,decayScale:.72}},enabled:true,solo:false,gain:.88,gestureId:'generated',mappings:[mapping('width-body','gesture.width','recipe.mapping.bodyGain',[0,1],[.72,1.28],'smoothstep')]},{id:'resonance',label:'Resonance',source:{type:'resonant-body',id:'impact-resonance',params:{modeLimit:5,decayScale:1.35,frequencyScale:.92}},enabled:true,solo:false,gain:.52,gestureId:'generated',mappings:[mapping('deviation-decay','gesture.deviation','object.modal.decayScale',[0,1],[.82,1.34],'ease-out')]},{id:'debris',label:'Debris',source:{type:'accent',id:'debris',params:{density:7,decayMs:16,frequencyHz:920}},enabled:true,solo:false,gain:.34,gestureId:'generated',mappings:[mapping('wiggle-residual','gesture.wiggle','recipe.mapping.residualGain',[0,1],[.5,1.25],'smoothstep')]}]);
  if(semanticType==='mechanism')return withLayerDefaults([{id:'mechanism-bed',label:'Mechanism bed',source:{type:'binding'},enabled:true,solo:false,gain:1,gestureId:'generated',mappings:[mapping('speed-friction','native.speed','recipe.mapping.frictionGain',[0,5],[.15,.62],'ease-in')]}]);
  return withLayerDefaults([{id:'primary',label:title(semanticType),source:{type:'binding'},enabled:true,solo:false,gain:1,gestureId:'generated',mappings:[]}]);
}
export function recommendedMappingsForLayer(semanticType,layerId){const layer=defaultLayersForSemanticType(semanticType).find(row=>row.id===layerId);return layer?structuredClone(layer.mappings||[]):null;}
export const generatedGestureForSegment=(sceneIntent,segment)=>({id:'generated',label:'Generated motion',kind:'generated',points:generatedGesturePoints(sceneIntent,segment)});
export function buildDefaultSoundScore(sceneIntent,{sceneIntentId='scene-intent'}={}){
  const interval=sceneIntent?.interval||{},startFrame=Math.round(finite(interval.startFrame,sceneIntent?.motion?.samples?.[0]?.frame||0)),endFrame=Math.round(finite(interval.endFrame,sceneIntent?.motion?.samples?.at(-1)?.frame??startFrame)),proofFrame=Math.round(finite(interval.proofFrame,endFrame));
  const sourceSegments=(sceneIntent?.segments?.length?sceneIntent.segments:[{id:sceneIntent?.action||'motion',startFrame,endFrame}]).flatMap(row=>splitMotionPhases(row,sceneIntent)),counts=new Map();
  const segments=sourceSegments.map((source,index)=>{const semanticType=semanticTypeForSegment(source,sceneIntent),serial=(counts.get(semanticType)||0)+1;counts.set(semanticType,serial);const gameRange=frameRange([source.startFrame,source.endFrame],[startFrame,endFrame]),proofFrames=proofFrame>=gameRange[0]&&proofFrame<=gameRange[1]&&semanticType==='impact'?[proofFrame]:[],context=semanticType==='impact'?2:0,authoringRange=[Math.max(startFrame,gameRange[0]-context),Math.min(endFrame,gameRange[1]+context)];return{id:`${semanticType}-${serial}`,label:title(semanticType),semanticType,sourceSegment:String(source.id||index),gameRange,authoringRange,proofFrames,layers:defaultLayersForSemanticType(semanticType),gestures:[]};});
  for(const segment of segments)segment.gestures=[generatedGestureForSegment(sceneIntent,segment)];
  const actor=String(sceneIntent?.target?.family||sceneIntent?.target?.object||sceneIntent?.event||'actor');return{schema:SOUND_SCORE_SCHEMA,sceneIntentId:String(sceneIntentId),sequence:{actor,startFrame,endFrame},segments};
}
export const selectedScoreSegment=(score,id)=>score?.segments?.find(row=>row.id===id)||score?.segments?.[0]||null;
export function authoringRangeForTiming(score,segmentId,timing={}){const segment=selectedScoreSegment(score,segmentId);if(!segment)return null;const sequence=score?.sequence||{},game=segment.gameRange||[0,0],current=segment.authoringRange||game,min=Number(sequence.startFrame??current[0]??game[0]),max=Number(sequence.endFrame??current[1]??game[1]);let start=Number(current[0]),end=Number(current[1]);if(Number.isFinite(Number(timing?.startFrame)))start=Math.max(min,Math.min(Number(game[0]),Math.round(Number(timing.startFrame))));if(Number.isFinite(Number(timing?.endFrame)))end=Math.min(max,Math.max(Number(game[1]),Math.round(Number(timing.endFrame))));if(end<start)end=start;return[start,end];}
export function selectedPlaybackRange(score,scene,segmentId,{mode='context',contextFrames=2,customRange=null}={}){const segment=selectedScoreSegment(score,segmentId),game=segment?.gameRange||[score?.sequence?.startFrame??0,score?.sequence?.endFrame??0],min=Number(scene?.minFrame??score?.sequence?.startFrame??game[0]),max=Number(scene?.maxFrame??score?.sequence?.endFrame??game[1]),exact={startFrame:Number(game[0]),endFrame:Number(game[1])};if(mode==='exact')return exact;if(mode==='custom'&&Array.isArray(customRange)&&customRange.length===2){const start=Math.max(min,Math.min(Number(customRange[0]),exact.startFrame)),end=Math.min(max,Math.max(Number(customRange[1]),exact.endFrame));return{startFrame:start,endFrame:Math.max(start,end)};}const context=Math.max(0,Math.round(Number(contextFrames)||0));return{startFrame:Math.max(min,exact.startFrame-context),endFrame:Math.min(max,exact.endFrame+context)};}
export function playbackRange(score,scene,scope='selected',segmentId=null){if(scope==='scene')return{startFrame:Number(scene?.minFrame??score?.sequence?.startFrame??0),endFrame:Number(scene?.maxFrame??score?.sequence?.endFrame??0)};if(scope==='sequence')return{startFrame:Number(score?.sequence?.startFrame??scene?.startFrame??0),endFrame:Number(score?.sequence?.endFrame??scene?.endFrame??0)};const segment=selectedScoreSegment(score,segmentId),range=segment?.authoringRange||[score?.sequence?.startFrame??0,score?.sequence?.endFrame??0];return{startFrame:Number(range[0]),endFrame:Number(range[1])};}
export function adjacentPlaybackRange(score,segmentId,{contextFrames=2}={}){const segments=[...(score?.segments||[])].sort((a,b)=>Number(a.gameRange?.[0])-Number(b.gameRange?.[0]));if(segments.length<2)return null;let index=segments.findIndex(row=>row.id===segmentId);if(index<0)index=0;const left=index<segments.length-1?segments[index]:segments[index-1],right=index<segments.length-1?segments[index+1]:segments[index],context=Math.max(0,Math.round(Number(contextFrames)||0)),start=Math.max(Number(score?.sequence?.startFrame??left.gameRange?.[0]??0),Number(left.gameRange?.[1]??left.gameRange?.[0]??0)-context),end=Math.min(Number(score?.sequence?.endFrame??right.gameRange?.[1]??start),Number(right.gameRange?.[0]??right.gameRange?.[1]??start)+context);return{startFrame:start,endFrame:Math.max(start,end),from:left.id,to:right.id};}

function allMotionRows(sceneIntent){return (sceneIntent?.motion?.samples||[]).slice().sort((a,b)=>finite(a.frame)-finite(b.frame));}
function motionRows(sceneIntent,segment){const range=segment?.gameRange||[0,0];return allMotionRows(sceneIntent).filter(row=>finite(row.frame)>=finite(range[0])&&finite(row.frame)<=finite(range[1]));}
function distanceAtProgress(rows,progress){if(rows.length<2)return 0;const p=clamp(finite(progress),0,1),position=p*(rows.length-1),whole=Math.floor(position),fraction=position-whole;let distance=0;for(let index=1;index<=whole;index+=1)distance+=Math.hypot(finite(rows[index]?.dx),finite(rows[index]?.dy));if(whole<rows.length-1)distance+=fraction*Math.hypot(finite(rows[whole+1]?.dx),finite(rows[whole+1]?.dy));return distance;}
function distanceAtFrame(rows,frame){if(rows.length<2)return 0;const target=finite(frame,finite(rows[0]?.frame));if(target<=finite(rows[0]?.frame))return 0;let distance=0;for(let index=1;index<rows.length;index+=1){const leftFrame=finite(rows[index-1]?.frame),rightFrame=finite(rows[index]?.frame,leftFrame+1),step=Math.hypot(finite(rows[index]?.dx),finite(rows[index]?.dy));if(target>=rightFrame){distance+=step;continue;}if(target>leftFrame)distance+=step*clamp((target-leftFrame)/Math.max(1e-9,rightFrame-leftFrame),0,1);break;}return distance;}
function sampleAtProgress(rows,progress){if(!rows.length)return null;const p=clamp(finite(progress),0,1),index=p*(rows.length-1),a=Math.floor(index),b=Math.min(rows.length-1,Math.ceil(index)),t=index-a,left=rows[a],right=rows[b];const mix=key=>lerp(finite(left?.[key]),finite(right?.[key]),t);return{frame:mix('frame'),dx:mix('dx'),dy:mix('dy'),speed:lerp(Number.isFinite(Number(left?.speed))?finite(left.speed):Math.hypot(finite(left?.dx),finite(left?.dy)),Number.isFinite(Number(right?.speed))?finite(right.speed):Math.hypot(finite(right?.dx),finite(right?.dy)),t),acceleration:lerp(finite(left?.acceleration??left?.accel),finite(right?.acceleration??right?.accel),t)};}
function gesturePoint(gesture,progress){const points=gesture?.points||[];if(!points.length)return null;const p=clamp(finite(progress),0,1);let before=points[0],after=points.at(-1);for(const point of points){if(finite(point.progress)<=p)before=point;if(finite(point.progress)>=p){after=point;break;}}const span=Math.max(1e-9,finite(after.progress)-finite(before.progress)),t=clamp((p-finite(before.progress))/span,0,1),mix=key=>lerp(finite(before?.[key]),finite(after?.[key]),t);return{progress:p,x:mix('x'),y:mix('y'),pressure:mix('pressure'),width:mix('width'),drawSpeed:mix('drawSpeed')};}
function gestureDerived(gesture,progress,channel){const points=gesture?.points||[],point=gesturePoint(gesture,progress);if(!point)return 0;if(channel==='pressure')return point.pressure;if(channel==='width')return Number.isFinite(Number(point.width))&&point.width!==0?point.width:point.pressure;if(channel==='deviation')return Math.abs(point.y-.5)*2;if(channel==='drawSpeed')return point.drawSpeed;if(channel==='phase')return point.progress;if(channel==='frequency'){if(points.length<2)return 0;const index=Math.max(0,Math.min(points.length-1,Math.round(clamp(finite(progress),0,1)*(points.length-1)))),a=points[Math.max(0,index-1)],b=points[index],c=points[Math.min(points.length-1,index+1)],span=Math.max(1e-9,finite(c.progress)-finite(a.progress)),variation=Math.abs(finite(b.y)-finite(a.y))+Math.abs(finite(c.y)-finite(b.y));return clamp(variation/span/4,0,1);}if(channel==='curvature'||channel==='wiggle'){if(points.length<3)return 0;const index=Math.max(1,Math.min(points.length-2,Math.round(clamp(finite(progress),0,1)*(points.length-1)))),a=points[index-1],b=points[index],c=points[index+1],slopeA=(finite(b.y)-finite(a.y))/Math.max(1e-9,finite(b.progress)-finite(a.progress)),slopeB=(finite(c.y)-finite(b.y))/Math.max(1e-9,finite(c.progress)-finite(b.progress)),bend=Math.abs(slopeB-slopeA);return channel==='curvature'?clamp(bend/8,0,1):clamp(bend/4,0,1);}return 0;}
function mappingSourceValue(source,{sceneIntent,segment,gesture,progress=.5}={}){const key=String(source||'');if(key==='manual.constant')return 1;if(key==='native.progress')return clamp(finite(progress),0,1);const rows=motionRows(sceneIntent,segment),sample=sampleAtProgress(rows,progress);if(key==='native.speed')return finite(sample?.speed);if(key==='native.velocityX')return finite(sample?.dx);if(key==='native.velocityY')return finite(sample?.dy);if(key==='native.acceleration')return finite(sample?.acceleration);if(key==='native.distance')return distanceAtProgress(rows,progress);if(key==='native.proofDistance'){const proof=finite(segment?.proofFrames?.[0],finite(sceneIntent?.interval?.proofFrame,sample?.frame)),all=allMotionRows(sceneIntent);return distanceAtFrame(all,sample?.frame)-distanceAtFrame(all,proof);}if(key.startsWith('gesture.'))return gestureDerived(gesture,progress,key.slice(8));return 0;}
function automationValue(points,progress){const rows=(Array.isArray(points)?points:[]).slice().sort((a,b)=>finite(a?.progress)-finite(b?.progress));if(!rows.length)return 1;const p=clamp(finite(progress),0,1);let before=rows[0],after=rows.at(-1);for(const row of rows){if(finite(row?.progress)<=p)before=row;if(finite(row?.progress)>=p){after=row;break;}}const span=Math.max(1e-9,finite(after?.progress)-finite(before?.progress)),t=clamp((p-finite(before?.progress))/span,0,1);return lerp(finite(before?.value),finite(after?.value),t);}
function envelopeValue(envelope,progress){const attackEnd=clamp(finite(envelope?.attackEnd,.2),0,1),releaseStart=clamp(finite(envelope?.releaseStart,.8),attackEnd,1),p=clamp(finite(progress),0,1);if(p<attackEnd)return attackEnd<=1e-9?1:p/attackEnd;if(p>releaseStart)return releaseStart>=1-1e-9?1:(1-p)/(1-releaseStart);return 1;}
function curveValue(curve,t){const x=clamp(t,0,1);if(curve==='ease-in')return x*x;if(curve==='ease-out')return 1-(1-x)*(1-x);if(curve==='smoothstep')return x*x*(3-2*x);return x;}
function variationNoise(seed,index){let x=((Number(seed)||0)|0)^Math.imul((index+1)|0,0x9e3779b1);x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return(x>>>0)/0xffffffff*2-1;}
function mappingVariation(variation,progress){const amount=clamp(finite(variation?.amount),0,1);if(amount<=0)return 0;const cycles=clamp(finite(variation?.rateCycles,4),.25,32),seed=Math.round(finite(variation?.seedOffset)),position=clamp(finite(progress),0,1)*cycles,a=Math.floor(position),b=a+1,t=curveValue('smoothstep',position-a);return lerp(variationNoise(seed,a),variationNoise(seed,b),t)*amount;}
export function evaluateMapping(mapping,context={}){const input=Array.isArray(mapping?.inputRange)&&mapping.inputRange.length===2?mapping.inputRange:[0,1],output=Array.isArray(mapping?.outputRange)&&mapping.outputRange.length===2?mapping.outputRange:[0,1],source=String(mapping?.source||''),raw=source==='manual.automation'?automationValue(mapping?.automation,context?.progress??.5):source==='manual.envelope'?envelopeValue(mapping?.envelope,context?.progress??.5):mappingSourceValue(mapping?.source,context),span=finite(input[1])-finite(input[0]);let t=Math.abs(span)<1e-9?0:(raw-finite(input[0]))/span;if(mapping?.clamp!==false)t=clamp(t,0,1);t=curveValue(mapping?.curve,t);const base=lerp(finite(output[0]),finite(output[1]),t),spanOut=Math.abs(finite(output[1])-finite(output[0])),variation=mappingVariation(mapping?.variation,context?.progress??.5);let value=base+variation*spanOut;if(mapping?.clamp!==false)value=clamp(value,Math.min(finite(output[0]),finite(output[1])),Math.max(finite(output[0]),finite(output[1])));return{sourceValue:raw,normalized:t,value,variation};}
export function representativeProgress(segment){if(segment?.proofFrames?.length){const [start,end]=segment.gameRange||[0,1],span=Math.max(1,end-start);return clamp((finite(segment.proofFrames[0])-finite(start))/span,0,1);}return .5;}
function deepMerge(base,override){if(!override||typeof override!=='object'||Array.isArray(override))return base;const out={...(base||{})};for(const [key,value] of Object.entries(override)){if(value&&typeof value==='object'&&!Array.isArray(value)&&out[key]&&typeof out[key]==='object'&&!Array.isArray(out[key]))out[key]=deepMerge(out[key],value);else if(value===null)delete out[key];else out[key]=value;}return out;}
function setPath(root,path,value){const parts=String(path).split('.').filter(Boolean);let cursor=root;for(const part of parts.slice(0,-1))cursor=cursor[part]??={};cursor[parts.at(-1)]=value;}
export function compileLayerMappings(sceneIntent,segment,layer,{progress=representativeProgress(segment)}={}){const gestures=segment?.gestures||[],gesture=gestures.find(row=>row.id===layer?.gestureId)||gestures[0]||null,values={},evaluations=[];for(const map of layer?.mappings||[]){if(map?.enabled===false||!map?.target)continue;const evaluated=evaluateMapping(map,{sceneIntent,segment,gesture,progress});values[map.target]=evaluated.value;evaluations.push({layerId:layer.id,mappingId:map.id,target:map.target,...evaluated});}return{progress,values,evaluations};}
export function mappingValuesToAdjustments(values={}){const overrides={};let strength=null;for(const [target,value] of Object.entries(values||{})){if(target==='binding.strength'){strength=clamp(value,0,1);continue;}const [kind,...rest]=String(target).split('.');if(!['recipe','object','material','style'].includes(kind)||!rest.length)continue;overrides[kind]??={};setPath(overrides[kind],rest.join('.'),value);}return{overrides,strength};}
export function compileLayerControlSignals(sceneIntent,segment,layer,{samples=64}={}){const count=Math.max(2,Math.min(512,Math.round(finite(samples,64)))),targets={};for(let index=0;index<count;index++){const progress=index/(count-1),compiled=compileLayerMappings(sceneIntent,segment,layer,{progress});for(const [target,value] of Object.entries(compiled.values))(targets[target]??=[]).push(value);}return{samples:count,targets};}
export function resolveLinkedSegment(score,segmentOrId,seen=new Set()){const segment=typeof segmentOrId==='string'?score?.segments?.find(row=>row.id===segmentOrId):segmentOrId;if(!segment)return null;const sourceId=String(segment.linkedFromSegmentId||'');if(!sourceId)return segment;if(seen.has(segment.id))throw new Error(`Sound Score segment link cycle at ${segment.id}`);const source=score?.segments?.find(row=>row.id===sourceId);if(!source)throw new Error(`Sound Score segment ${segment.id} links missing segment ${sourceId}`);const next=new Set(seen);next.add(segment.id);const resolved=resolveLinkedSegment(score,source,next);return{...segment,layers:structuredClone(resolved.layers||[]),gestures:structuredClone(resolved.gestures||[])}};
export function synchronizeLinkedSegments(score){for(const segment of score?.segments||[]){if(!segment.linkedFromSegmentId)continue;const resolved=resolveLinkedSegment(score,segment);segment.layers=structuredClone(resolved.layers||[]);segment.gestures=structuredClone(resolved.gestures||[]);}return score;}
export function copySegmentDesign(score,sourceId,targetId,{link=false}={}){const source=resolveLinkedSegment(score,sourceId),target=score?.segments?.find(row=>row.id===targetId);if(!source||!target||source.id===target.id||source.semanticType!==target.semanticType)return false;target.layers=structuredClone(source.layers||[]);target.gestures=structuredClone(source.gestures||[]);if(link)target.linkedFromSegmentId=source.id;else delete target.linkedFromSegmentId;synchronizeLinkedSegments(score);return true;}
export function compileSoundScoreAdjustments(score,sceneIntent,{segmentId=null,semanticType=null}={}){if(!score?.segments?.length||!sceneIntent)return{overrides:{},strength:null,segment:null,evaluations:[]};const proof=finite(sceneIntent?.interval?.proofFrame,NaN),selected=score.segments.find(row=>row.id===segmentId)||score.segments.find(row=>semanticType&&row.semanticType===semanticType)||score.segments.find(row=>Number.isFinite(proof)&&row.proofFrames?.includes(proof))||score.segments[0],segment=resolveLinkedSegment(score,selected),layers=(segment.layers||[]).filter(row=>row.enabled!==false),solo=layers.filter(row=>row.solo),active=solo.length?solo:layers,progress=representativeProgress(segment),targets=new Map(),evaluations=[];for(const layer of active){const compiled=compileLayerMappings(sceneIntent,segment,layer,{progress}),weight=Math.max(0,finite(layer.gain,1));for(const [target,value] of Object.entries(compiled.values)){const row=targets.get(target)||{sum:0,weight:0};row.sum+=value*weight;row.weight+=weight;targets.set(target,row);}evaluations.push(...compiled.evaluations);}const values=Object.fromEntries([...targets].map(([target,row])=>[target,row.weight>0?row.sum/row.weight:0])),adjusted=mappingValuesToAdjustments(values);return{...adjusted,segment,evaluations};}
export function applySoundScoreToBinding(binding,score,sceneIntent,options={}){const compiled=compileSoundScoreAdjustments(score,sceneIntent,options);return{binding:{...binding,strength:compiled.strength??binding.strength,overrides:deepMerge(binding.overrides||{},compiled.overrides)},compiled};}
export function applySoundScoreLayerToBinding(binding,sceneIntent,segment,layer){const compiled=compileLayerMappings(sceneIntent,segment,layer),adjusted=mappingValuesToAdjustments(compiled.values);return{binding:{...binding,strength:adjusted.strength??binding.strength,overrides:deepMerge(binding.overrides||{},adjusted.overrides)},compiled};}
